"""
物品配置文件 - 所有可获得物品的定义

每个物品的配置参数说明：

基础属性：
- name (str): 物品名称，显示给用户的物品名字
- weight (int): 物品权重，用于随机抽取时的概率计算，数值越大越容易抽到
- min_count (int): 单次获得的最小数量
- max_count (int): 单次获得的最大数量
- description (str): 物品描述文本，通常包含emoji和物品介绍
- category (str): 物品分类（如"食物"、"礼物"、"用品"等）

经济属性：
- sell_price (int): 出售价格，玩家卖出物品时的金币收入
- buy_price (int): 购买价格，玩家从商店购买时需要的金币（可选）

效果属性（用于喂食或使用物品时的效果）：
- affection_value (float): 好感度增加值，使用后增加的好感度
- hunger_effect (int): 饥饿值影响，正数减少饥饿，负数增加饥饿
- mood_effect (int): 心情值影响，正数提升心情，负数降低心情
- cleanliness_effect (int): 清洁度影响，正数提升清洁度，负数降低清洁度
- health_effect (int): 健康值影响，正数提升健康，负数降低健康

注意事项：
- 所有效果值为0表示该物品对对应属性无影响
- weight值影响物品在随机抽取中的出现概率
- 价格设置需要考虑游戏经济平衡
"""

# 物品列表配置
ITEMS_LIST = [
    {
        "name": "巧克力",
        "weight": 15,
        "min_count": 1,
        "max_count": 3,
        "description": "🍫 甜甜的巧克力，可以让老婆心情变好",
        "sell_price": 8,
        "buy_price": 20,
        "affection_value": 0.3,
        "hunger_effect": 10,
        "mood_effect": 15,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "食物"
    },
    {
        "name": "鲜花",
        "weight": 15,
        "min_count": 1,
        "max_count": 2,
        "description": "🌸 美丽的鲜花，浪漫的象征",
        "sell_price": 12,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "浪漫",
        "buy_price": 30
    },
    {
        "name": "小石头",
        "weight": 12,
        "min_count": 1,
        "max_count": 5,
        "description": "🪨 普通的小石头，也许有特殊用途",
        "sell_price": 2,
        "affection_value": 0.1,
        "hunger_effect": 0,
        "mood_effect": 5,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "普通",
        "buy_price": 5
    },
    {
        "name": "树叶",
        "weight": 12,
        "min_count": 1,
        "max_count": 4,
        "description": "🍃 新鲜的绿叶，大自然的馈赠",
        "sell_price": 3,
        "affection_value": 0.1,
        "hunger_effect": 0,
        "mood_effect": 8,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "普通",
        "buy_price": 7
    },
    {
        "name": "羽毛",
        "weight": 10,
        "min_count": 1,
        "max_count": 3,
        "description": "🪶 轻盈的羽毛，来自未知的鸟类",
        "sell_price": 5,
        "affection_value": 0.15,
        "hunger_effect": 0,
        "mood_effect": 10,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "普通",
        "buy_price": 12
    },
    {
        "name": "贝壳",
        "weight": 10,
        "min_count": 1,
        "max_count": 2,
        "description": "🐚 海边的贝壳，听得到海的声音",
        "sell_price": 7,
        "affection_value": 0.2,
        "hunger_effect": 0,
        "mood_effect": 12,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品",
        "buy_price": 17
    },
    {
        "name": "果实",
        "weight": 10,
        "min_count": 1,
        "max_count": 4,
        "description": "🍎 新鲜的果实，营养丰富",
        "sell_price": 6,
        "affection_value": 0.2,
        "hunger_effect": 15,
        "mood_effect": 10,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "食物",
        "buy_price": 15
    },
    {
        "name": "蘑菇",
        "weight": 8,
        "min_count": 1,
        "max_count": 3,
        "description": "🍄 神秘的蘑菇，不知道能不能吃",
        "sell_price": 4,
        "affection_value": 0.15,
        "hunger_effect": 8,
        "mood_effect": 5,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "食物",
        "buy_price": 10
    },
    {
        "name": "宝石",
        "weight": 3,
        "min_count": 1,
        "max_count": 2,
        "description": "💎 闪闪发光的宝石，价值不菲",
        "sell_price": 5000,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 30,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "珍贵",
        "buy_price": 7500
    },
    {
        "name": "珍珠",
        "weight": 2,
        "min_count": 1,
        "max_count": 1,
        "description": "🦪 海中的珍珠，稀有珍贵",
        "sell_price": 6000,
        "affection_value": 1.0,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "珍贵",
        "buy_price": 9000
    },
    {
        "name": "钻戒",
        "weight": 1.5,
        "min_count": 1,
        "max_count": 1,
        "description": "💍 闪亮的钻戒，求婚必备",
        "sell_price": 10000,
        "affection_value": 1.5,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "珍贵",
        "buy_price": 15000
    },
    {
        "name": "黄金",
        "weight": 1.5,
        "min_count": 1,
        "max_count": 1,
        "description": "🥇 纯金制品，永远保值",
        "sell_price": 8000,
        "affection_value": 1.2,
        "hunger_effect": 0,
        "mood_effect": 40,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "珍贵",
        "buy_price": 12000
    },
    {
        "name": "水晶",
        "weight": 2,
        "min_count": 1,
        "max_count": 1,
        "description": "🔮 透明的水晶，据说有神奇力量",
        "sell_price": 3000,
        "affection_value": 0.9,
        "hunger_effect": 0,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 10,
        "category": "神秘",
        "buy_price": 4500
    },
    {
        "name": "香水",
        "weight": 6,
        "min_count": 1,
        "max_count": 1,
        "description": "🌺 迷人的香水，让人心醉",
        "sell_price": 45,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 25,
        "health_effect": 0,
        "category": "浪漫",
        "buy_price": 112
    },
    {
        "name": "丝绸",
        "weight": 5,
        "min_count": 1,
        "max_count": 2,
        "description": "🧵 柔滑的丝绸，触感极佳",
        "sell_price": 35,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "奢侈品",
        "buy_price": 87
    },
    {
        "name": "药草",
        "weight": 6,
        "min_count": 1,
        "max_count": 3,
        "description": "🌿 神奇的药草，可以治病",
        "sell_price": 15,
        "affection_value": 0.3,
        "hunger_effect": 0,
        "mood_effect": 5,
        "cleanliness_effect": 0,
        "health_effect": 20,
        "category": "药物",
        "buy_price": 37
    },
    {
        "name": "龙蛋",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "🥚 传说中的龙蛋，孵化后不得了",
        "sell_price": 150000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "传说",
        "buy_price": 225000
    },
    {
        "name": "魔法石",
        "weight": 0.5,
        "min_count": 1,
        "max_count": 1,
        "description": "✨ 蕴含魔力的石头，闪烁着神秘光芒",
        "sell_price": 15000,
        "affection_value": 1.5,
        "hunger_effect": 0,
        "mood_effect": 30,
        "cleanliness_effect": 0,
        "health_effect": 15,
        "category": "神秘",
        "buy_price": 22500
    },
    {
        "name": "独角兽之角",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "🦄 独角兽的角，拥有治愈一切的力量",
        "sell_price": 80000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 30,
        "health_effect": 50,
        "category": "传说",
        "buy_price": 120000
    },
    {
        "name": "凤凰羽毛",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "🔥 凤凰的羽毛，可以重生",
        "sell_price": 60000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 40,
        "cleanliness_effect": 0,
        "health_effect": 50,
        "category": "传说",
        "buy_price": 90000
    },
    {
        "name": "时空碎片",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "⏰ 时空的碎片，可以窥探过去未来",
        "sell_price": 100000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "传说",
        "buy_price": 150000
    },
    {
        "name": "彩虹糖",
        "weight": 3,
        "min_count": 1,
        "max_count": 3,
        "description": "🌈 七彩的糖果，据说能实现愿望",
        "sell_price": 25,
        "affection_value": 0.6,
        "hunger_effect": 12,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "神秘",
        "buy_price": 62
    },
    {
        "name": "星辰沙",
        "weight": 0.5,
        "min_count": 1,
        "max_count": 2,
        "description": "⭐ 来自星空的沙子，闪闪发光",
        "sell_price": 12000,
        "affection_value": 1.3,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": 20,
        "health_effect": 0,
        "category": "神秘",
        "buy_price": 18000
    },
    {
        "name": "月光露",
        "weight": 0.8,
        "min_count": 1,
        "max_count": 1,
        "description": "🌙 月圆之夜收集的露水，清澈透明",
        "sell_price": 8000,
        "affection_value": 1.1,
        "hunger_effect": 5,
        "mood_effect": 25,
        "cleanliness_effect": 30,
        "health_effect": 10,
        "category": "神秘",
        "buy_price": 12000
    },
    {
        "name": "雷电瓶",
        "weight": 0.3,
        "min_count": 1,
        "max_count": 1,
        "description": "⚡ 装着雷电的瓶子，危险但有用",
        "sell_price": 25000,
        "affection_value": 1.8,
        "hunger_effect": 0,
        "mood_effect": 30,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "神秘",
        "buy_price": 37500
    },
    {
        "name": "梦境捕捉器",
        "weight": 0.3,
        "min_count": 1,
        "max_count": 1,
        "description": "💭 可以捕捉美梦的神器",
        "sell_price": 20000,
        "affection_value": 1.7,
        "hunger_effect": 0,
        "mood_effect": 40,
        "cleanliness_effect": 0,
        "health_effect": 15,
        "category": "神秘",
        "buy_price": 30000
    },
    {
        "name": "幸运草",
        "weight": 4,
        "min_count": 1,
        "max_count": 2,
        "description": "🍀 四叶草，象征着好运",
        "sell_price": 20,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "幸运",
        "buy_price": 50
    },
    {
        "name": "许愿瓶",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "💌 装着愿望的瓶子，也许会实现",
        "sell_price": 40,
        "affection_value": 0.7,
        "hunger_effect": 0,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "浪漫",
        "buy_price": 100
    },
    {
        "name": "古董戒指",
        "weight": 1,
        "min_count": 1,
        "max_count": 1,
        "description": "💍 古老的戒指，有着神秘的历史",
        "sell_price": 8000,
        "affection_value": 1.2,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "古董",
        "buy_price": 12000
    },
    {
        "name": "神秘卷轴",
        "weight": 2,
        "min_count": 1,
        "max_count": 1,
        "description": "📜 写着未知文字的卷轴",
        "sell_price": 100,
        "affection_value": 0.9,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "神秘",
        "buy_price": 200
    },
    {
        "name": "琥珀",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "🟡 透明的琥珀，里面封印着古老的昆虫",
        "sell_price": 70,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 22,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "古董",
        "buy_price": 175
    },
    {
        "name": "海螺",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "🐚 美丽的海螺，吹响它会有奇迹发生",
        "sell_price": 30,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品",
        "buy_price": 75
    },
    {
        "name": "流星石",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "☄️ 从天而降的陨石，蕴含宇宙之力",
        "sell_price": 45000,
        "affection_value": 1.9,
        "hunger_effect": 0,
        "mood_effect": 45,
        "cleanliness_effect": 0,
        "health_effect": 20,
        "category": "传说",
        "buy_price": 67500
    },
    {
        "name": "精灵眼泪",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "🧚‍♀️ 精灵哭泣时的眼泪，极其珍贵",
        "sell_price": 75000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 40,
        "health_effect": 30,
        "category": "传说",
        "buy_price": 112500
    },
    {
        "name": "天使之翼",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "👼 天使的翅膀羽毛，圣洁无比",
        "sell_price": 90000,
        "affection_value": 1.9,
        "hunger_effect": 0,
        "mood_effect": 45,
        "cleanliness_effect": 35,
        "health_effect": 25,
        "category": "传说",
        "buy_price": 135000
    },
    {
        "name": "恶魔之心",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "😈 恶魔的心脏结晶，黑暗力量的源泉",
        "sell_price": 85000,
        "affection_value": 1.9,
        "hunger_effect": 0,
        "mood_effect": 30,
        "cleanliness_effect": 0,
        "health_effect": 40,
        "category": "传说",
        "buy_price": 127500
    },
    {
        "name": "蜂蜜",
        "weight": 6,
        "min_count": 1,
        "max_count": 2,
        "description": "🍯 甜美的蜂蜜，小熊最爱",
        "sell_price": 12,
        "affection_value": 0.3,
        "hunger_effect": 12,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "食物",
        "buy_price": 30
    },
    {
        "name": "奶酪",
        "weight": 5,
        "min_count": 1,
        "max_count": 2,
        "description": "🧀 浓郁的奶酪，营养丰富",
        "sell_price": 10,
        "affection_value": 0.25,
        "hunger_effect": 18,
        "mood_effect": 10,
        "cleanliness_effect": 0,
        "health_effect": 8,
        "category": "食物",
        "buy_price": 25
    },
    {
        "name": "面包",
        "weight": 8,
        "min_count": 1,
        "max_count": 3,
        "description": "🍞 新鲜出炉的面包，香气扑鼻",
        "sell_price": 8,
        "affection_value": 0.25,
        "hunger_effect": 80,
        "mood_effect": 12,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "食物",
        "buy_price": 500000
    },
    {
        "name": "糖果",
        "weight": 10,
        "min_count": 1,
        "max_count": 5,
        "description": "🍬 各种口味的糖果，甜到心里",
        "sell_price": 5,
        "affection_value": 0.2,
        "hunger_effect": 8,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "食物",
        "buy_price": 12
    },
    {
        "name": "咖啡豆",
        "weight": 4,
        "min_count": 1,
        "max_count": 3,
        "description": "☕ 优质咖啡豆，提神醒脑",
        "sell_price": 25,
        "affection_value": 0.45,
        "hunger_effect": 5,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "食物",
        "buy_price": 62
    },
    {
        "name": "茶叶",
        "weight": 5,
        "min_count": 1,
        "max_count": 2,
        "description": "🍵 上等茶叶，清香怡人",
        "sell_price": 20,
        "affection_value": 0.4,
        "hunger_effect": 3,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 10,
        "category": "食物",
        "buy_price": 50
    },
    {
        "name": "小镜子",
        "weight": 5,
        "min_count": 1,
        "max_count": 1,
        "description": "🪞 精致的小镜子，照见真心",
        "sell_price": 18,
        "affection_value": 0.35,
        "hunger_effect": 0,
        "mood_effect": 15,
        "cleanliness_effect": 10,
        "health_effect": 0,
        "category": "工具",
        "buy_price": 45
    },
    {
        "name": "发簪",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "📍 精美的发簪，古典优雅",
        "sell_price": 35,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 25,
        "cleanliness_effect": 5,
        "health_effect": 0,
        "category": "饰品",
        "buy_price": 87
    },
    {
        "name": "手帕",
        "weight": 6,
        "min_count": 1,
        "max_count": 2,
        "description": "🤧 柔软的手帕，绅士必备",
        "sell_price": 12,
        "affection_value": 0.25,
        "hunger_effect": 0,
        "mood_effect": 8,
        "cleanliness_effect": 15,
        "health_effect": 0,
        "category": "日用品",
        "buy_price": 30
    },
    {
        "name": "扇子",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "🪭 雅致的扇子，夏日清凉",
        "sell_price": 25,
        "affection_value": 0.45,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 8,
        "health_effect": 0,
        "category": "工具",
        "buy_price": 62
    },
    {
        "name": "音乐盒",
        "weight": 1,
        "min_count": 1,
        "max_count": 1,
        "description": "🎵 精美的音乐盒，奏响动人旋律",
        "sell_price": 3500,
        "affection_value": 1.1,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "奢侈品",
        "buy_price": 5250
    },
    {
        "name": "风铃",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "🎐 清脆的风铃，风吹过会有天籁之音",
        "sell_price": 30,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "装饰品",
        "buy_price": 75
    },
    {
        "name": "香皂",
        "weight": 8,
        "min_count": 1,
        "max_count": 3,
        "description": "🧼 清香的香皂，洗去一身疲惫",
        "sell_price": 8,
        "affection_value": 0.2,
        "hunger_effect": 0,
        "mood_effect": 12,
        "cleanliness_effect": 30,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 20
    },
    {
        "name": "毛巾",
        "weight": 6,
        "min_count": 1,
        "max_count": 2,
        "description": "🏖️ 柔软的毛巾，温暖贴心",
        "sell_price": 12,
        "affection_value": 0.25,
        "hunger_effect": 0,
        "mood_effect": 15,
        "cleanliness_effect": 25,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 30
    },
    {
        "name": "洗发水",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "🧴 高级洗发水，让头发如丝般顺滑",
        "sell_price": 25,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 35,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 62
    },
    {
        "name": "沐浴露",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "🛁 芬芳的沐浴露，洗去一天的疲劳",
        "sell_price": 22,
        "affection_value": 0.35,
        "hunger_effect": 0,
        "mood_effect": 18,
        "cleanliness_effect": 40,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 55
    },
    {
        "name": "牙刷",
        "weight": 10,
        "min_count": 1,
        "max_count": 2,
        "description": "🪥 柔软的牙刷，守护口腔健康",
        "sell_price": 5,
        "affection_value": 0.15,
        "hunger_effect": 0,
        "mood_effect": 8,
        "cleanliness_effect": 20,
        "health_effect": 5,
        "category": "清洁用品",
        "buy_price": 12
    },
    {
        "name": "洗面奶",
        "weight": 5,
        "min_count": 1,
        "max_count": 1,
        "description": "🧴 温和的洗面奶，护肤第一步",
        "sell_price": 30,
        "affection_value": 0.45,
        "hunger_effect": 0,
        "mood_effect": 15,
        "cleanliness_effect": 30,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 75
    },
    {
        "name": "创口贴",
        "weight": 12,
        "min_count": 1,
        "max_count": 5,
        "description": "🩹 可爱的创口贴，治愈小伤口",
        "sell_price": 3,
        "affection_value": 0.1,
        "hunger_effect": 0,
        "mood_effect": 8,
        "cleanliness_effect": 0,
        "health_effect": 15,
        "category": "药物",
        "buy_price": 7
    },
    {
        "name": "维生素",
        "weight": 6,
        "min_count": 1,
        "max_count": 3,
        "description": "💊 营养维生素，补充每日所需",
        "sell_price": 18,
        "affection_value": 0.3,
        "hunger_effect": 0,
        "mood_effect": 10,
        "cleanliness_effect": 0,
        "health_effect": 25,
        "category": "药物",
        "buy_price": 45
    },
    {
        "name": "感冒药",
        "weight": 4,
        "min_count": 1,
        "max_count": 2,
        "description": "💊 感冒药片，对抗感冒病毒",
        "sell_price": 25,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 5,
        "cleanliness_effect": 0,
        "health_effect": 35,
        "category": "药物",
        "buy_price": 62
    },
    {
        "name": "蜂胶",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "🍯 天然蜂胶，增强免疫力",
        "sell_price": 45,
        "affection_value": 0.6,
        "hunger_effect": 5,
        "mood_effect": 15,
        "cleanliness_effect": 0,
        "health_effect": 30,
        "category": "药物",
        "buy_price": 112
    },
    {
        "name": "体温计",
        "weight": 5,
        "min_count": 1,
        "max_count": 1,
        "description": "🌡️ 电子体温计，关注健康状况",
        "sell_price": 35,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 12,
        "cleanliness_effect": 0,
        "health_effect": 20,
        "category": "医疗用品",
        "buy_price": 87
    },
    {
        "name": "眼药水",
        "weight": 7,
        "min_count": 1,
        "max_count": 2,
        "description": "👁️ 舒缓眼药水，缓解眼部疲劳",
        "sell_price": 15,
        "affection_value": 0.25,
        "hunger_effect": 0,
        "mood_effect": 10,
        "cleanliness_effect": 5,
        "health_effect": 20,
        "category": "药物",
        "buy_price": 37
    },
    {
        "name": "群主的女装照",
        "weight": 1,
        "min_count": 1,
        "max_count": 1,
        "description": "📸 群主珍藏的女装照片，据说看了会变可爱",
        "sell_price": 50,
        "buy_price": 888,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": -10,
        "health_effect": 0,
        "category": "滑稽"
    },
    {
        "name": "管理的绿帽子",
        "weight": 2,
        "min_count": 1,
        "max_count": 1,
        "description": "💚 神秘的绿色帽子，戴上就有管理的权威",
        "sell_price": 30,
        "buy_price": 666,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "滑稽"
    },
    {
        "name": "暴雪帝国编年史",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "📚 银河掠夺者中最强传说军团的史书，记录了暴雪帝国的无敌传奇",
        "sell_price": 20,
        "buy_price": 1314,
        "affection_value": 1,
        "hunger_effect": 999,
        "mood_effect": 999,
        "cleanliness_effect": 999,
        "health_effect": 999,
        "category": "滑稽"
    },
    {
        "name": "单身狗粮",
        "weight": 5,
        "min_count": 1,
        "max_count": 3,
        "description": "🍖 专为单身人士调配的狗粮，味道意外不错",
        "sell_price": 8,
        "buy_price": 18,
        "affection_value": 0.3,
        "hunger_effect": 15,
        "mood_effect": -5,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "滑稽"
    },
    # ===== 快餐店食物 =====
    {
        "name": "薯条",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍟 金黄薯条，外酥内软的经典小食",
        "sell_price": 12,
        "buy_price": 15,
        "affection_value": 0.3,
        "hunger_effect": 20,
        "mood_effect": 15,
        "cleanliness_effect": -2,
        "health_effect": -2,
        "category": "快餐"
    },
    {
        "name": "蛋挞",
        "weight": 0,
        "min_count": 1,
        "max_count": 2,
        "description": "🥧 港式蛋挞，香滑蛋液配酥脆挞皮",
        "sell_price": 10,
        "buy_price": 13,
        "affection_value": 0.4,
        "hunger_effect": 18,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "快餐"
    },
    {
        "name": "吮指原味鸡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 经典吮指原味鸡，香嫩多汁的炸鸡块",
        "sell_price": 18,
        "buy_price": 22,
        "affection_value": 0.5,
        "hunger_effect": 30,
        "mood_effect": 20,
        "cleanliness_effect": -3,
        "health_effect": 0,
        "category": "快餐"
    },
    {
        "name": "新奥尔良烤鸡腿堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍔 新奥尔良烤鸡腿堡，香辣烤鸡腿配新鲜蔬菜",
        "sell_price": 30,
        "buy_price": 36,
        "affection_value": 0.8,
        "hunger_effect": 40,
        "mood_effect": 30,
        "cleanliness_effect": -5,
        "health_effect": -3,
        "category": "快餐"
    },
    {
        "name": "双层吉士汉堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍔 双层吉士汉堡，双层牛肉饼配浓郁芝士",
        "sell_price": 32,
        "buy_price": 38,
        "affection_value": 0.9,
        "hunger_effect": 45,
        "mood_effect": 32,
        "cleanliness_effect": -6,
        "health_effect": -4,
        "category": "快餐"
    },
    {
        "name": "上校鸡块",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 上校鸡块，一口一个的香脆享受",
        "sell_price": 22,
        "buy_price": 26,
        "affection_value": 0.6,
        "hunger_effect": 28,
        "mood_effect": 18,
        "cleanliness_effect": -3,
        "health_effect": 0,
        "category": "快餐"
    },
    {
        "name": "奥尔良烤鸡翅",
        "weight": 0,
        "min_count": 1,
        "max_count": 2,
        "description": "🍗 奥尔良烤鸡翅，香料烤制的美味鸡翅",
        "sell_price": 25,
        "buy_price": 30,
        "affection_value": 0.7,
        "hunger_effect": 32,
        "mood_effect": 22,
        "cleanliness_effect": -4,
        "health_effect": 2,
        "category": "快餐"
    },
    {
        "name": "全家桶",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 全家桶套餐，多种炸鸡满足全家人的需求",
        "sell_price": 75,
        "buy_price": 92,
        "affection_value": 1.4,
        "hunger_effect": 75,
        "mood_effect": 45,
        "cleanliness_effect": -12,
        "health_effect": -8,
        "category": "快餐"
    },
    {
        "name": "麦旋风",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍦 麦旋风冰淇淋，奥利奥碎片混合的甜蜜享受",
        "sell_price": 16,
        "buy_price": 20,
        "affection_value": 0.6,
        "hunger_effect": 22,
        "mood_effect": 35,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "快餐"
    },
    {
        "name": "儿童套餐",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🎁 儿童套餐，小汉堡+小薯条+玩具的温馨组合",
        "sell_price": 42,
        "buy_price": 50,
        "affection_value": 1.1,
        "hunger_effect": 50,
        "mood_effect": 40,
        "cleanliness_effect": -4,
        "health_effect": -2,
        "category": "快餐"
    },
    {
        "name": "vivo50餐",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 vivo50限定套餐，据说吃了能让手机运行更流畅？",
        "sell_price": 88,
        "buy_price": 250,
        "affection_value": 1.8,
        "hunger_effect": 50,
        "mood_effect": 66,
        "cleanliness_effect": -10,
        "health_effect": -5,
        "category": "滑稽"
    },
    # ===== 苍蝇馆子地方菜 =====
    {
        "name": "正宗兰州拉面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 地道兰州牛肉拉面，清香的汤头配上劲道的面条",
        "sell_price": 120,
        "buy_price": 320,
        "affection_value": 1.5,
        "hunger_effect": 60,
        "mood_effect": 45,
        "cleanliness_effect": -8,
        "health_effect": 10,
        "category": "地方菜"
    },
    {
        "name": "重庆小面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌶️ 重庆麻辣小面，香辣过瘾的经典川渝美味",
        "sell_price": 110,
        "buy_price": 300,
        "affection_value": 1.4,
        "hunger_effect": 55,
        "mood_effect": 50,
        "cleanliness_effect": -5,
        "health_effect": 5,
        "category": "地方菜"
    },
    {
        "name": "广式肠粉",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥢 广东茶楼经典肠粉，嫩滑米皮包裹鲜美馅料",
        "sell_price": 100,
        "buy_price": 280,
        "affection_value": 1.2,
        "hunger_effect": 50,
        "mood_effect": 40,
        "cleanliness_effect": 0,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "上海生煎包",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥟 上海老字号生煎包，外焦内嫩汁水丰富",
        "sell_price": 130,
        "buy_price": 350,
        "affection_value": 1.6,
        "hunger_effect": 65,
        "mood_effect": 48,
        "cleanliness_effect": -6,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "北京炸酱面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍝 老北京炸酱面，浓郁酱香配上爽口菜码",
        "sell_price": 115,
        "buy_price": 310,
        "affection_value": 1.3,
        "hunger_effect": 58,
        "mood_effect": 42,
        "cleanliness_effect": -7,
        "health_effect": 6,
        "category": "地方菜"
    },
    {
        "name": "西安肉夹馍",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥙 陕西特色肉夹馍，酥脆白吉馍夹香烂腊汁肉",
        "sell_price": 125,
        "buy_price": 330,
        "affection_value": 1.5,
        "hunger_effect": 62,
        "mood_effect": 46,
        "cleanliness_effect": -10,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "东北锅包肉",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 东北经典锅包肉，外酥内嫩酸甜可口",
        "sell_price": 140,
        "buy_price": 380,
        "affection_value": 1.7,
        "hunger_effect": 70,
        "mood_effect": 55,
        "cleanliness_effect": -12,
        "health_effect": 5,
        "category": "地方菜"
    },
    {
        "name": "湖南臭豆腐",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🧄 湖南长沙臭豆腐，闻着臭吃着香的独特美味",
        "sell_price": 90,
        "buy_price": 260,
        "affection_value": 1.1,
        "hunger_effect": 45,
        "mood_effect": 38,
        "cleanliness_effect": -15,
        "health_effect": 0,
        "category": "地方菜"
    },
    {
        "name": "云南过桥米线",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍲 云南特色过桥米线，鲜美高汤涮煮各式配菜",
        "sell_price": 135,
        "buy_price": 360,
        "affection_value": 1.6,
        "hunger_effect": 68,
        "mood_effect": 52,
        "cleanliness_effect": -3,
        "health_effect": 15,
        "category": "地方菜"
    },
    {
        "name": "新疆大盘鸡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐔 新疆大盘鸡，香辣鸡肉配土豆宽面条",
        "sell_price": 150,
        "buy_price": 400,
        "affection_value": 1.8,
        "hunger_effect": 75,
        "mood_effect": 58,
        "cleanliness_effect": -10,
        "health_effect": 10,
        "category": "地方菜"
    },
    {
        "name": "四川麻婆豆腐",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌶️ 四川经典麻婆豆腐，麻辣鲜香下饭神器",
        "sell_price": 105,
        "buy_price": 290,
        "affection_value": 1.3,
        "hunger_effect": 52,
        "mood_effect": 44,
        "cleanliness_effect": -8,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "山东煎饼果子",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥞 天津山东煎饼果子，薄脆配鸡蛋的街头经典",
        "sell_price": 95,
        "buy_price": 270,
        "affection_value": 1.2,
        "hunger_effect": 48,
        "mood_effect": 40,
        "cleanliness_effect": -5,
        "health_effect": 6,
        "category": "地方菜"
    },
    {
        "name": "福建沙茶面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦐 福建沙茶面，独特沙茶酱调制的鲜香面条",
        "sell_price": 120,
        "buy_price": 320,
        "affection_value": 1.4,
        "hunger_effect": 58,
        "mood_effect": 46,
        "cleanliness_effect": -6,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "河南胡辣汤",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍯 河南胡辣汤，香辣浓稠的经典早餐汤品",
        "sell_price": 85,
        "buy_price": 250,
        "affection_value": 1.0,
        "hunger_effect": 42,
        "mood_effect": 35,
        "cleanliness_effect": -4,
        "health_effect": 5,
        "category": "地方菜"
    },
    {
        "name": "贵州酸汤鱼",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐟 贵州特色酸汤鱼，酸辣开胃的苗家风味",
        "sell_price": 160,
        "buy_price": 420,
        "affection_value": 1.9,
        "hunger_effect": 78,
        "mood_effect": 60,
        "cleanliness_effect": -8,
        "health_effect": 18,
        "category": "地方菜"
    },
    # ===== 超市新增商品 =====
    {
        "name": "关东煮",
        "weight": 8,
        "min_count": 1,
        "max_count": 2,
        "description": "🍢 日式关东煮，温热的汤汁配各种食材",
        "sell_price": 18,
        "buy_price": 35,
        "affection_value": 0.4,
        "hunger_effect": 25,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "日式料理"
    },
    {
        "name": "炒面面包",
        "weight": 6,
        "min_count": 1,
        "max_count": 1,
        "description": "🍞 日式炒面面包，面包里夹着香喷喷的炒面",
        "sell_price": 15,
        "buy_price": 28,
        "affection_value": 0.3,
        "hunger_effect": 30,
        "mood_effect": 15,
        "cleanliness_effect": -3,
        "health_effect": 0,
        "category": "日式料理"
    },
    {
        "name": "猪排饭团",
        "weight": 7,
        "min_count": 1,
        "max_count": 1,
        "description": "🍙 日式猪排饭团，香脆猪排配软糯米饭",
        "sell_price": 22,
        "buy_price": 42,
        "affection_value": 0.5,
        "hunger_effect": 35,
        "mood_effect": 25,
        "cleanliness_effect": -2,
        "health_effect": 8,
        "category": "日式料理"
    },
    {
        "name": "菠萝包",
        "weight": 8,
        "min_count": 1,
        "max_count": 2,
        "description": "🍍 港式菠萝包，酥脆表皮配松软内馅",
        "sell_price": 12,
        "buy_price": 25,
        "affection_value": 0.35,
        "hunger_effect": 22,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "港式茶餐厅"
    },
    {
        "name": "跳蛋",
        "weight": 1,
        "min_count": 1,
        "max_count": 1,
        "description": "🥚 神秘的小玩具，据说能带来不一样的体验",
        "sell_price": 88,
        "buy_price": 199,
        "affection_value": 1.2,
        "hunger_effect": 0,
        "mood_effect": 233,
        "cleanliness_effect": -15,
        "health_effect": 233,
        "category": "成人用品"
    },
    {
        "name": "避孕套",
        "weight": 5,
        "min_count": 1,
        "max_count": 3,
        "description": "💊 安全防护用品，负责任的表现",
        "sell_price": 8,
        "buy_price": 15,
        "affection_value": 0.2,
        "hunger_effect": 0,
        "mood_effect": 88,
        "cleanliness_effect": -20,
        "health_effect": 88,
        "category": "成人用品"
    },
    # ===== 新增苍蝇馆子地方菜 =====
    {
        "name": "隆江猪脚饭",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 潮汕特色隆江猪脚饭，卤制猪脚香糯软烂",
        "sell_price": 145,
        "buy_price": 390,
        "affection_value": 1.7,
        "hunger_effect": 72,
        "mood_effect": 55,
        "cleanliness_effect": -10,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "柳州螺蛳粉",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐌 广西柳州螺蛳粉，酸辣鲜美的重口味米粉",
        "sell_price": 125,
        "buy_price": 340,
        "affection_value": 1.5,
        "hunger_effect": 60,
        "mood_effect": 48,
        "cleanliness_effect": -12,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "广式烧鹅",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦆 广东传统烧鹅，皮脆肉嫩油而不腻",
        "sell_price": 180,
        "buy_price": 480,
        "affection_value": 2.0,
        "hunger_effect": 85,
        "mood_effect": 68,
        "cleanliness_effect": -15,
        "health_effect": 15,
        "category": "地方菜"
    },
    {
        "name": "杭州西湖醋鱼",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐟 杭州名菜西湖醋鱼，酸甜清香的江南美味",
        "sell_price": 165,
        "buy_price": 440,
        "affection_value": 1.8,
        "hunger_effect": 75,
        "mood_effect": 62,
        "cleanliness_effect": -5,
        "health_effect": 20,
        "category": "地方菜"
    },
    {
        "name": "天津狗不理包子",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥟 天津老字号狗不理包子，皮薄馅大汁多",
        "sell_price": 155,
        "buy_price": 420,
        "affection_value": 1.8,
        "hunger_effect": 70,
        "mood_effect": 58,
        "cleanliness_effect": -8,
        "health_effect": 14,
        "category": "地方菜"
    },
    {
        "name": "苏州阳春面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 苏州传统阳春面，清汤细面简单而不简约",
        "sell_price": 118,
        "buy_price": 315,
        "affection_value": 1.4,
        "hunger_effect": 55,
        "mood_effect": 45,
        "cleanliness_effect": -3,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "成都夫妻肺片",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌶️ 成都经典夫妻肺片，麻辣鲜香的凉菜代表",
        "sell_price": 138,
        "buy_price": 370,
        "affection_value": 1.6,
        "hunger_effect": 65,
        "mood_effect": 52,
        "cleanliness_effect": -8,
        "health_effect": 10,
        "category": "地方菜"
    },
    {
        "name": "武汉热干面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 武汉特色热干面，浓郁芝麻酱拌制的干面",
        "sell_price": 112,
        "buy_price": 300,
        "affection_value": 1.3,
        "hunger_effect": 58,
        "mood_effect": 42,
        "cleanliness_effect": -6,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "长沙口味虾",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦐 长沙夜宵经典口味虾，麻辣鲜香的小龙虾",
        "sell_price": 170,
        "buy_price": 450,
        "affection_value": 1.9,
        "hunger_effect": 78,
        "mood_effect": 65,
        "cleanliness_effect": -18,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "东坡肘子",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 四川名菜东坡肘子，软糯香甜的传统川菜",
        "sell_price": 185,
        "buy_price": 490,
        "affection_value": 2.1,
        "hunger_effect": 88,
        "mood_effect": 70,
        "cleanliness_effect": -12,
        "health_effect": 18,
        "category": "地方菜"
    },
    {
        "name": "南京盐水鸭",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦆 南京特产盐水鸭，皮白肉嫩鲜美清淡",
        "sell_price": 158,
        "buy_price": 425,
        "affection_value": 1.8,
        "hunger_effect": 73,
        "mood_effect": 60,
        "cleanliness_effect": -6,
        "health_effect": 16,
        "category": "地方菜"
    },
    {
        "name": "沈阳白肉血肠",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 东北特色白肉血肠，浓郁的东北风味",
        "sell_price": 148,
        "buy_price": 395,
        "affection_value": 1.7,
        "hunger_effect": 70,
        "mood_effect": 55,
        "cleanliness_effect": -8,
        "health_effect": 14,
        "category": "地方菜"
    },
    {
        "name": "太原刀削面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 山西特色刀削面，刀削出的独特面条形状",
        "sell_price": 115,
        "buy_price": 308,
        "affection_value": 1.3,
        "hunger_effect": 56,
        "mood_effect": 44,
        "cleanliness_effect": -5,
        "health_effect": 9,
        "category": "地方菜"
    },
    {
        "name": "宁夏手抓羊肉",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐑 宁夏传统手抓羊肉，鲜嫩无膻味的西北特色",
        "sell_price": 195,
        "buy_price": 520,
        "affection_value": 2.2,
        "hunger_effect": 92,
        "mood_effect": 75,
        "cleanliness_effect": -15,
        "health_effect": 22,
        "category": "地方菜"
    },
    {
        "name": "内蒙古烤羊腿",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 内蒙古烤羊腿，草原上的豪放美食",
        "sell_price": 220,
        "buy_price": 580,
        "affection_value": 2.5,
        "hunger_effect": 100,
        "mood_effect": 85,
        "cleanliness_effect": -20,
        "health_effect": 25,
        "category": "地方菜"
    }
]
