"""
物品配置文件 - 所有可获得物品的定义

每个物品的配置参数说明：

基础属性：
- name (str): 物品名称，显示给用户的物品名字
- weight (int): 物品权重，用于随机抽取时的概率计算，数值越大越容易抽到
- min_count (int): 单次获得的最小数量
- max_count (int): 单次获得的最大数量
- description (str): 物品描述文本，通常包含emoji和物品介绍
- category (str): 物品分类（如"食物"、"礼物"、"用品"等）

经济属性：
- sell_price (int): 出售价格，玩家卖出物品时的金币收入
- buy_price (int): 购买价格，玩家从商店购买时需要的金币（可选）

效果属性（用于喂食或使用物品时的效果）：
- affection_value (float): 好感度增加值，使用后增加的好感度
- hunger_effect (int): 饥饿值影响，正数减少饥饿，负数增加饥饿
- mood_effect (int): 心情值影响，正数提升心情，负数降低心情
- cleanliness_effect (int): 清洁度影响，正数提升清洁度，负数降低清洁度
- health_effect (int): 健康值影响，正数提升健康，负数降低健康

注意事项：
- 所有效果值为0表示该物品对对应属性无影响
- weight值影响物品在随机抽取中的出现概率
- 价格设置需要考虑游戏经济平衡
"""

# 物品列表配置
ITEMS_LIST = [
    {
        "name": "巧克力",
        "weight": 15,
        "min_count": 1,
        "max_count": 3,
        "description": "🍫 甜甜的巧克力，可以让老婆心情变好",
        "sell_price": 8,
        "buy_price": 20,
        "affection_value": 0.3,
        "hunger_effect": 10,
        "mood_effect": 15,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "食物"
    },
    {
        "name": "鲜花",
        "weight": 15,
        "min_count": 1,
        "max_count": 2,
        "description": "🌸 美丽的鲜花，浪漫的象征",
        "sell_price": 12,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "浪漫",
        "buy_price": 30
    },
    {
        "name": "小石头",
        "weight": 12,
        "min_count": 1,
        "max_count": 5,
        "description": "🪨 普通的小石头，也许有特殊用途",
        "sell_price": 2,
        "affection_value": 0.1,
        "hunger_effect": 0,
        "mood_effect": 5,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "普通",
        "buy_price": 5
    },
    {
        "name": "树叶",
        "weight": 12,
        "min_count": 1,
        "max_count": 4,
        "description": "🍃 新鲜的绿叶，大自然的馈赠",
        "sell_price": 3,
        "affection_value": 0.1,
        "hunger_effect": 0,
        "mood_effect": 8,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "普通",
        "buy_price": 7
    },
    {
        "name": "羽毛",
        "weight": 10,
        "min_count": 1,
        "max_count": 3,
        "description": "🪶 轻盈的羽毛，来自未知的鸟类",
        "sell_price": 5,
        "affection_value": 0.15,
        "hunger_effect": 0,
        "mood_effect": 10,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "普通",
        "buy_price": 12
    },
    {
        "name": "贝壳",
        "weight": 10,
        "min_count": 1,
        "max_count": 2,
        "description": "🐚 海边的贝壳，听得到海的声音",
        "sell_price": 7,
        "affection_value": 0.2,
        "hunger_effect": 0,
        "mood_effect": 12,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品",
        "buy_price": 17
    },
    {
        "name": "果实",
        "weight": 10,
        "min_count": 1,
        "max_count": 4,
        "description": "🍎 新鲜的果实，营养丰富",
        "sell_price": 6,
        "affection_value": 0.2,
        "hunger_effect": 15,
        "mood_effect": 10,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "食物",
        "buy_price": 15
    },
    {
        "name": "蘑菇",
        "weight": 8,
        "min_count": 1,
        "max_count": 3,
        "description": "🍄 神秘的蘑菇，不知道能不能吃",
        "sell_price": 4,
        "affection_value": 0.15,
        "hunger_effect": 8,
        "mood_effect": 5,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "食物",
        "buy_price": 10
    },
    {
        "name": "宝石",
        "weight": 3,
        "min_count": 1,
        "max_count": 2,
        "description": "💎 闪闪发光的宝石，价值不菲",
        "sell_price": 5000,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 30,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "珍贵",
        "buy_price": 7500
    },
    {
        "name": "珍珠",
        "weight": 2,
        "min_count": 1,
        "max_count": 1,
        "description": "🦪 海中的珍珠，稀有珍贵",
        "sell_price": 6000,
        "affection_value": 1.0,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "珍贵",
        "buy_price": 9000
    },
    {
        "name": "钻戒",
        "weight": 1.5,
        "min_count": 1,
        "max_count": 1,
        "description": "💍 闪亮的钻戒，求婚必备",
        "sell_price": 10000,
        "affection_value": 1.5,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "珍贵",
        "buy_price": 15000
    },
    {
        "name": "黄金",
        "weight": 1.5,
        "min_count": 1,
        "max_count": 1,
        "description": "🥇 纯金制品，永远保值",
        "sell_price": 8000,
        "affection_value": 1.2,
        "hunger_effect": 0,
        "mood_effect": 40,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "珍贵",
        "buy_price": 12000
    },
    {
        "name": "水晶",
        "weight": 2,
        "min_count": 1,
        "max_count": 1,
        "description": "🔮 透明的水晶，据说有神奇力量",
        "sell_price": 3000,
        "affection_value": 0.9,
        "hunger_effect": 0,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 10,
        "category": "神秘",
        "buy_price": 4500
    },
    {
        "name": "香水",
        "weight": 6,
        "min_count": 1,
        "max_count": 1,
        "description": "🌺 迷人的香水，让人心醉",
        "sell_price": 45,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 25,
        "health_effect": 0,
        "category": "浪漫",
        "buy_price": 112
    },
    {
        "name": "丝绸",
        "weight": 5,
        "min_count": 1,
        "max_count": 2,
        "description": "🧵 柔滑的丝绸，触感极佳",
        "sell_price": 35,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "奢侈品",
        "buy_price": 87
    },
    {
        "name": "药草",
        "weight": 6,
        "min_count": 1,
        "max_count": 3,
        "description": "🌿 神奇的药草，可以治病",
        "sell_price": 15,
        "affection_value": 0.3,
        "hunger_effect": 0,
        "mood_effect": 5,
        "cleanliness_effect": 0,
        "health_effect": 20,
        "category": "药物",
        "buy_price": 37
    },
    {
        "name": "龙蛋",
        "weight": 0.2,
        "min_count": 1,
        "max_count": 1,
        "description": "🥚 传说中的龙蛋，孵化后不得了",
        "sell_price": 150000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "传说",
        "buy_price": 225000
    },
    {
        "name": "魔法石",
        "weight": 0.5,
        "min_count": 1,
        "max_count": 1,
        "description": "✨ 蕴含魔力的石头，闪烁着神秘光芒",
        "sell_price": 15000,
        "affection_value": 1.5,
        "hunger_effect": 0,
        "mood_effect": 30,
        "cleanliness_effect": 0,
        "health_effect": 15,
        "category": "神秘",
        "buy_price": 22500
    },
    {
        "name": "独角兽之角",
        "weight": 0.05,
        "min_count": 1,
        "max_count": 1,
        "description": "🦄 独角兽的角，拥有治愈一切的力量",
        "sell_price": 80000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 30,
        "health_effect": 50,
        "category": "传说",
        "buy_price": 120000
    },
    {
        "name": "凤凰羽毛",
        "weight": 0.05,
        "min_count": 1,
        "max_count": 1,
        "description": "🔥 凤凰的羽毛，可以重生",
        "sell_price": 60000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 40,
        "cleanliness_effect": 0,
        "health_effect": 50,
        "category": "传说",
        "buy_price": 90000
    },
    {
        "name": "时空碎片",
        "weight": 0.03,
        "min_count": 1,
        "max_count": 1,
        "description": "⏰ 时空的碎片，可以窥探过去未来",
        "sell_price": 100000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "传说",
        "buy_price": 150000
    },
    {
        "name": "彩虹糖",
        "weight": 3,
        "min_count": 1,
        "max_count": 3,
        "description": "🌈 七彩的糖果，据说能实现愿望",
        "sell_price": 25,
        "affection_value": 0.6,
        "hunger_effect": 12,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "神秘",
        "buy_price": 62
    },
    {
        "name": "星辰沙",
        "weight": 0.5,
        "min_count": 1,
        "max_count": 2,
        "description": "⭐ 来自星空的沙子，闪闪发光",
        "sell_price": 12000,
        "affection_value": 1.3,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": 20,
        "health_effect": 0,
        "category": "神秘",
        "buy_price": 18000
    },
    {
        "name": "月光露",
        "weight": 0.8,
        "min_count": 1,
        "max_count": 1,
        "description": "🌙 月圆之夜收集的露水，清澈透明",
        "sell_price": 8000,
        "affection_value": 1.1,
        "hunger_effect": 5,
        "mood_effect": 25,
        "cleanliness_effect": 30,
        "health_effect": 10,
        "category": "神秘",
        "buy_price": 12000
    },
    {
        "name": "雷电瓶",
        "weight": 0.3,
        "min_count": 1,
        "max_count": 1,
        "description": "⚡ 装着雷电的瓶子，危险但有用",
        "sell_price": 25000,
        "affection_value": 1.8,
        "hunger_effect": 0,
        "mood_effect": 30,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "神秘",
        "buy_price": 37500
    },
    {
        "name": "梦境捕捉器",
        "weight": 0.3,
        "min_count": 1,
        "max_count": 1,
        "description": "💭 可以捕捉美梦的神器",
        "sell_price": 20000,
        "affection_value": 1.7,
        "hunger_effect": 0,
        "mood_effect": 40,
        "cleanliness_effect": 0,
        "health_effect": 15,
        "category": "神秘",
        "buy_price": 30000
    },
    {
        "name": "幸运草",
        "weight": 4,
        "min_count": 1,
        "max_count": 2,
        "description": "🍀 四叶草，象征着好运",
        "sell_price": 20,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "幸运",
        "buy_price": 50
    },
    {
        "name": "许愿瓶",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "💌 装着愿望的瓶子，也许会实现",
        "sell_price": 40,
        "affection_value": 0.7,
        "hunger_effect": 0,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "浪漫",
        "buy_price": 100
    },
    {
        "name": "古董戒指",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "💍 古老的戒指，有着神秘的历史",
        "sell_price": 8000,
        "affection_value": 1.2,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "古董",
        "buy_price": 12000
    },
    {
        "name": "神秘卷轴",
        "weight": 2,
        "min_count": 1,
        "max_count": 1,
        "description": "📜 写着未知文字的卷轴",
        "sell_price": 100,
        "affection_value": 0.9,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "神秘",
        "buy_price": 200
    },
    {
        "name": "琥珀",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "🟡 透明的琥珀，里面封印着古老的昆虫",
        "sell_price": 70,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 22,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "古董",
        "buy_price": 175
    },
    {
        "name": "海螺",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "🐚 美丽的海螺，吹响它会有奇迹发生",
        "sell_price": 30,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品",
        "buy_price": 75
    },
    {
        "name": "流星石",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "☄️ 从天而降的陨石，蕴含宇宙之力",
        "sell_price": 45000,
        "affection_value": 1.9,
        "hunger_effect": 0,
        "mood_effect": 45,
        "cleanliness_effect": 0,
        "health_effect": 20,
        "category": "传说",
        "buy_price": 67500
    },
    {
        "name": "精灵眼泪",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "🧚‍♀️ 精灵哭泣时的眼泪，极其珍贵",
        "sell_price": 75000,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 50,
        "cleanliness_effect": 40,
        "health_effect": 30,
        "category": "传说",
        "buy_price": 112500
    },
    {
        "name": "天使之翼",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "👼 天使的翅膀羽毛，圣洁无比",
        "sell_price": 90000,
        "affection_value": 1.9,
        "hunger_effect": 0,
        "mood_effect": 45,
        "cleanliness_effect": 35,
        "health_effect": 25,
        "category": "传说",
        "buy_price": 135000
    },
    {
        "name": "恶魔之心",
        "weight": 0.001,
        "min_count": 1,
        "max_count": 1,
        "description": "😈 恶魔的心脏结晶，黑暗力量的源泉",
        "sell_price": 85000,
        "affection_value": 1.9,
        "hunger_effect": 0,
        "mood_effect": 30,
        "cleanliness_effect": 0,
        "health_effect": 40,
        "category": "传说",
        "buy_price": 127500
    },
    {
        "name": "蜂蜜",
        "weight": 6,
        "min_count": 1,
        "max_count": 2,
        "description": "🍯 甜美的蜂蜜，小熊最爱",
        "sell_price": 12,
        "affection_value": 0.3,
        "hunger_effect": 12,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "食物",
        "buy_price": 30
    },
    {
        "name": "奶酪",
        "weight": 5,
        "min_count": 1,
        "max_count": 2,
        "description": "🧀 浓郁的奶酪，营养丰富",
        "sell_price": 10,
        "affection_value": 0.25,
        "hunger_effect": 18,
        "mood_effect": 10,
        "cleanliness_effect": 0,
        "health_effect": 8,
        "category": "食物",
        "buy_price": 25
    },
    {
        "name": "德国黑面包",
        "weight": 8,
        "min_count": 1,
        "max_count": 3,
        "description": "🍞 传说这条面包里夹带了一整个魏玛共和国，50万马克一个",
        "sell_price": 8,
        "affection_value": 0.25,
        "hunger_effect": 80,
        "mood_effect": 12,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "滑稽",
        "buy_price": 500000
    },
    {
        "name": "糖果",
        "weight": 10,
        "min_count": 1,
        "max_count": 5,
        "description": "🍬 各种口味的糖果，甜到心里",
        "sell_price": 5,
        "affection_value": 0.2,
        "hunger_effect": 8,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "食物",
        "buy_price": 12
    },
    {
        "name": "咖啡豆",
        "weight": 4,
        "min_count": 1,
        "max_count": 3,
        "description": "☕ 优质咖啡豆，提神醒脑",
        "sell_price": 25,
        "affection_value": 0.45,
        "hunger_effect": 5,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "食物",
        "buy_price": 62
    },
    {
        "name": "茶叶",
        "weight": 5,
        "min_count": 1,
        "max_count": 2,
        "description": "🍵 上等茶叶，清香怡人",
        "sell_price": 20,
        "affection_value": 0.4,
        "hunger_effect": 3,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 10,
        "category": "食物",
        "buy_price": 50
    },
    {
        "name": "小镜子",
        "weight": 5,
        "min_count": 1,
        "max_count": 1,
        "description": "🪞 精致的小镜子，照见真心",
        "sell_price": 18,
        "affection_value": 0.35,
        "hunger_effect": 0,
        "mood_effect": 15,
        "cleanliness_effect": 10,
        "health_effect": 0,
        "category": "工具",
        "buy_price": 45
    },
    {
        "name": "发簪",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "📍 精美的发簪，古典优雅",
        "sell_price": 35,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 25,
        "cleanliness_effect": 5,
        "health_effect": 0,
        "category": "饰品",
        "buy_price": 87
    },
    {
        "name": "手帕",
        "weight": 6,
        "min_count": 1,
        "max_count": 2,
        "description": "🤧 柔软的手帕，绅士必备",
        "sell_price": 12,
        "affection_value": 0.25,
        "hunger_effect": 0,
        "mood_effect": 8,
        "cleanliness_effect": 15,
        "health_effect": 0,
        "category": "日用品",
        "buy_price": 30
    },
    {
        "name": "扇子",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "🪭 雅致的扇子，夏日清凉",
        "sell_price": 25,
        "affection_value": 0.45,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 8,
        "health_effect": 0,
        "category": "工具",
        "buy_price": 62
    },
    {
        "name": "音乐盒",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🎵 精美的音乐盒，奏响动人旋律",
        "sell_price": 3500,
        "affection_value": 1.1,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "奢侈品",
        "buy_price": 5250
    },
    {
        "name": "风铃",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "🎐 清脆的风铃，风吹过会有天籁之音",
        "sell_price": 30,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "装饰品",
        "buy_price": 75
    },
    {
        "name": "香皂",
        "weight": 8,
        "min_count": 1,
        "max_count": 3,
        "description": "🧼 清香的香皂，洗去一身疲惫",
        "sell_price": 8,
        "affection_value": 0.2,
        "hunger_effect": 0,
        "mood_effect": 12,
        "cleanliness_effect": 30,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 20
    },
    {
        "name": "毛巾",
        "weight": 6,
        "min_count": 1,
        "max_count": 2,
        "description": "🏖️ 柔软的毛巾，温暖贴心",
        "sell_price": 12,
        "affection_value": 0.25,
        "hunger_effect": 0,
        "mood_effect": 15,
        "cleanliness_effect": 25,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 30
    },
    {
        "name": "洗发水",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "🧴 高级洗发水，让头发如丝般顺滑",
        "sell_price": 25,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 20,
        "cleanliness_effect": 35,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 62
    },
    {
        "name": "沐浴露",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "🛁 芬芳的沐浴露，洗去一天的疲劳",
        "sell_price": 22,
        "affection_value": 0.35,
        "hunger_effect": 0,
        "mood_effect": 18,
        "cleanliness_effect": 40,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 55
    },
    {
        "name": "牙刷",
        "weight": 10,
        "min_count": 1,
        "max_count": 2,
        "description": "🪥 柔软的牙刷，守护口腔健康",
        "sell_price": 5,
        "affection_value": 0.15,
        "hunger_effect": 0,
        "mood_effect": 8,
        "cleanliness_effect": 20,
        "health_effect": 5,
        "category": "清洁用品",
        "buy_price": 12
    },
    {
        "name": "洗面奶",
        "weight": 5,
        "min_count": 1,
        "max_count": 1,
        "description": "🧴 温和的洗面奶，护肤第一步",
        "sell_price": 30,
        "affection_value": 0.45,
        "hunger_effect": 0,
        "mood_effect": 15,
        "cleanliness_effect": 30,
        "health_effect": 0,
        "category": "清洁用品",
        "buy_price": 75
    },
    {
        "name": "创口贴",
        "weight": 12,
        "min_count": 1,
        "max_count": 5,
        "description": "🩹 可爱的创口贴，治愈小伤口",
        "sell_price": 3,
        "affection_value": 0.1,
        "hunger_effect": 0,
        "mood_effect": 8,
        "cleanliness_effect": 0,
        "health_effect": 15,
        "category": "药物",
        "buy_price": 7
    },
    {
        "name": "维生素",
        "weight": 6,
        "min_count": 1,
        "max_count": 3,
        "description": "💊 营养维生素，补充每日所需",
        "sell_price": 18,
        "affection_value": 0.3,
        "hunger_effect": 0,
        "mood_effect": 10,
        "cleanliness_effect": 0,
        "health_effect": 25,
        "category": "药物",
        "buy_price": 45
    },
    {
        "name": "感冒药",
        "weight": 4,
        "min_count": 1,
        "max_count": 2,
        "description": "💊 感冒药片，对抗感冒病毒",
        "sell_price": 25,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 5,
        "cleanliness_effect": 0,
        "health_effect": 35,
        "category": "药物",
        "buy_price": 62
    },
    {
        "name": "蜂胶",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "🍯 天然蜂胶，增强免疫力",
        "sell_price": 45,
        "affection_value": 0.6,
        "hunger_effect": 5,
        "mood_effect": 15,
        "cleanliness_effect": 0,
        "health_effect": 30,
        "category": "药物",
        "buy_price": 112
    },
    {
        "name": "体温计",
        "weight": 5,
        "min_count": 1,
        "max_count": 1,
        "description": "🌡️ 电子体温计，关注健康状况",
        "sell_price": 35,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 12,
        "cleanliness_effect": 0,
        "health_effect": 20,
        "category": "医疗用品",
        "buy_price": 87
    },
    {
        "name": "眼药水",
        "weight": 7,
        "min_count": 1,
        "max_count": 2,
        "description": "👁️ 舒缓眼药水，缓解眼部疲劳",
        "sell_price": 15,
        "affection_value": 0.25,
        "hunger_effect": 0,
        "mood_effect": 10,
        "cleanliness_effect": 5,
        "health_effect": 20,
        "category": "药物",
        "buy_price": 37
    },
    {
        "name": "群主的女装照",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "📸 群主珍藏的女装照片，据说看了会变可爱",
        "sell_price": 50,
        "buy_price": 888,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 35,
        "cleanliness_effect": -10,
        "health_effect": 0,
        "category": "滑稽"
    },
    {
        "name": "管理的绿帽子",
        "weight": 2,
        "min_count": 1,
        "max_count": 1,
        "description": "💚 神秘的绿色帽子，戴上就有管理的权威",
        "sell_price": 30,
        "buy_price": 666,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "滑稽"
    },
    {
        "name": "暴雪帝国编年史",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "📚 银河掠夺者中最强传说军团的史书，记录了暴雪帝国的无敌传奇",
        "sell_price": 20,
        "buy_price": 1314,
        "affection_value": 1,
        "hunger_effect": 999,
        "mood_effect": 999,
        "cleanliness_effect": 999,
        "health_effect": 999,
        "category": "滑稽"
    },
    {
        "name": "单身狗粮",
        "weight": 5,
        "min_count": 1,
        "max_count": 3,
        "description": "🍖 专为单身人士调配的狗粮，味道意外不错",
        "sell_price": 8,
        "buy_price": 18,
        "affection_value": 0.3,
        "hunger_effect": 15,
        "mood_effect": -5,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "滑稽"
    },
    # ===== 快餐店食物 =====
    {
        "name": "薯条",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍟 金黄薯条，外酥内软的经典小食",
        "sell_price": 12,
        "buy_price": 15,
        "affection_value": 0.3,
        "hunger_effect": 20,
        "mood_effect": 15,
        "cleanliness_effect": -2,
        "health_effect": -2,
        "category": "快餐"
    },
    {
        "name": "蛋挞",
        "weight": 0,
        "min_count": 1,
        "max_count": 2,
        "description": "🥧 港式蛋挞，香滑蛋液配酥脆挞皮",
        "sell_price": 10,
        "buy_price": 13,
        "affection_value": 0.4,
        "hunger_effect": 18,
        "mood_effect": 25,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "快餐"
    },
    {
        "name": "吮指原味鸡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 经典吮指原味鸡，香嫩多汁的炸鸡块",
        "sell_price": 18,
        "buy_price": 22,
        "affection_value": 0.5,
        "hunger_effect": 30,
        "mood_effect": 20,
        "cleanliness_effect": -3,
        "health_effect": 0,
        "category": "快餐"
    },
    {
        "name": "新奥尔良烤鸡腿堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍔 新奥尔良烤鸡腿堡，香辣烤鸡腿配新鲜蔬菜",
        "sell_price": 30,
        "buy_price": 36,
        "affection_value": 0.8,
        "hunger_effect": 40,
        "mood_effect": 30,
        "cleanliness_effect": -5,
        "health_effect": -3,
        "category": "快餐"
    },
    {
        "name": "双层吉士汉堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍔 双层吉士汉堡，双层牛肉饼配浓郁芝士",
        "sell_price": 32,
        "buy_price": 38,
        "affection_value": 0.9,
        "hunger_effect": 45,
        "mood_effect": 32,
        "cleanliness_effect": -6,
        "health_effect": -4,
        "category": "快餐"
    },
    {
        "name": "上校鸡块",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 上校鸡块，一口一个的香脆享受",
        "sell_price": 22,
        "buy_price": 26,
        "affection_value": 0.6,
        "hunger_effect": 28,
        "mood_effect": 18,
        "cleanliness_effect": -3,
        "health_effect": 0,
        "category": "快餐"
    },
    {
        "name": "奥尔良烤鸡翅",
        "weight": 0,
        "min_count": 1,
        "max_count": 2,
        "description": "🍗 奥尔良烤鸡翅，香料烤制的美味鸡翅",
        "sell_price": 25,
        "buy_price": 30,
        "affection_value": 0.7,
        "hunger_effect": 32,
        "mood_effect": 22,
        "cleanliness_effect": -4,
        "health_effect": 2,
        "category": "快餐"
    },
    {
        "name": "全家桶",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 全家桶套餐，多种炸鸡满足全家人的需求",
        "sell_price": 75,
        "buy_price": 92,
        "affection_value": 1.4,
        "hunger_effect": 75,
        "mood_effect": 45,
        "cleanliness_effect": -12,
        "health_effect": -8,
        "category": "快餐"
    },
    {
        "name": "麦旋风",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍦 麦旋风冰淇淋，奥利奥碎片混合的甜蜜享受",
        "sell_price": 16,
        "buy_price": 20,
        "affection_value": 0.6,
        "hunger_effect": 22,
        "mood_effect": 35,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "快餐"
    },
    {
        "name": "儿童套餐",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🎁 儿童套餐，小汉堡+小薯条+玩具的温馨组合",
        "sell_price": 42,
        "buy_price": 50,
        "affection_value": 1.1,
        "hunger_effect": 50,
        "mood_effect": 40,
        "cleanliness_effect": -4,
        "health_effect": -2,
        "category": "快餐"
    },
    {
        "name": "刀削面汉堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍔 创意汉堡，山西刀削面配牛肉饼的奇妙组合",
        "sell_price": 35,
        "buy_price": 42,
        "affection_value": 0.9,
        "hunger_effect": 48,
        "mood_effect": 35,
        "cleanliness_effect": -6,
        "health_effect": -5,
        "category": "快餐"
    },
    {
        "name": "北京烤鸭汉堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦆 奢华汉堡，正宗北京烤鸭片配黄瓜丝和甜面酱",
        "sell_price": 45,
        "buy_price": 55,
        "affection_value": 1.2,
        "hunger_effect": 55,
        "mood_effect": 45,
        "cleanliness_effect": -8,
        "health_effect": -3,
        "category": "快餐"
    },
    {
        "name": "丝瓜汤汉堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥒 清爽汉堡，丝瓜汤汁浸润的素食汉堡",
        "sell_price": 28,
        "buy_price": 35,
        "affection_value": 0.7,
        "hunger_effect": 35,
        "mood_effect": 25,
        "cleanliness_effect": -2,
        "health_effect": 8,
        "category": "快餐"
    },
    {
        "name": "麦辣鸡腿堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🔥 麦当劳经典辣味汉堡，香辣鸡腿配生菜",
        "sell_price": 33,
        "buy_price": 40,
        "affection_value": 0.8,
        "hunger_effect": 42,
        "mood_effect": 30,
        "cleanliness_effect": -5,
        "health_effect": -4,
        "category": "快餐"
    },
    {
        "name": "巨无霸汉堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍔 麦当劳招牌汉堡，双层牛肉饼配特制酱料",
        "sell_price": 40,
        "buy_price": 48,
        "affection_value": 1.0,
        "hunger_effect": 52,
        "mood_effect": 38,
        "cleanliness_effect": -7,
        "health_effect": -6,
        "category": "快餐"
    },
    {
        "name": "香辣鸡腿堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌶️ 肯德基经典辣味汉堡，香辣炸鸡腿配新鲜蔬菜",
        "sell_price": 34,
        "buy_price": 41,
        "affection_value": 0.8,
        "hunger_effect": 45,
        "mood_effect": 32,
        "cleanliness_effect": -6,
        "health_effect": -5,
        "category": "快餐"
    },
    {
        "name": "汉堡王皇堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "👑 汉堡王招牌汉堡，火烤牛肉饼的王者体验",
        "sell_price": 42,
        "buy_price": 50,
        "affection_value": 1.1,
        "hunger_effect": 55,
        "mood_effect": 40,
        "cleanliness_effect": -8,
        "health_effect": -7,
        "category": "快餐"
    },
    {
        "name": "德克士脆皮炸鸡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 德克士招牌炸鸡，外酥内嫩的秘制配方",
        "sell_price": 25,
        "buy_price": 30,
        "affection_value": 0.7,
        "hunger_effect": 35,
        "mood_effect": 25,
        "cleanliness_effect": -4,
        "health_effect": -3,
        "category": "快餐"
    },
    {
        "name": "板烧鸡腿堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 日式风味汉堡，照烧酱汁板烧鸡腿",
        "sell_price": 36,
        "buy_price": 43,
        "affection_value": 0.9,
        "hunger_effect": 46,
        "mood_effect": 34,
        "cleanliness_effect": -5,
        "health_effect": -3,
        "category": "快餐"
    },
    {
        "name": "鸡米花",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 肯德基小食，一口一个的香脆鸡米花",
        "sell_price": 15,
        "buy_price": 18,
        "affection_value": 0.4,
        "hunger_effect": 22,
        "mood_effect": 18,
        "cleanliness_effect": -2,
        "health_effect": -2,
        "category": "快餐"
    },
    {
        "name": "麦乐鸡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 麦当劳小食，四块装香脆鸡块",
        "sell_price": 16,
        "buy_price": 19,
        "affection_value": 0.4,
        "hunger_effect": 24,
        "mood_effect": 20,
        "cleanliness_effect": -2,
        "health_effect": -2,
        "category": "快餐"
    },
    {
        "name": "安格斯厚牛堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥩 高端汉堡，优质安格斯牛肉制作的厚实汉堡",
        "sell_price": 55,
        "buy_price": 65,
        "affection_value": 1.4,
        "hunger_effect": 65,
        "mood_effect": 50,
        "cleanliness_effect": -10,
        "health_effect": -8,
        "category": "快餐"
    },
    {
        "name": "鳕鱼堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐟 海鲜汉堡，新鲜鳕鱼排配柠檬塔塔酱",
        "sell_price": 38,
        "buy_price": 45,
        "affection_value": 1.0,
        "hunger_effect": 42,
        "mood_effect": 35,
        "cleanliness_effect": -3,
        "health_effect": 2,
        "category": "快餐"
    },
    {
        "name": "帕尼尼",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥖 意式热压三明治，酥脆外皮配丰富馅料",
        "sell_price": 32,
        "buy_price": 38,
        "affection_value": 0.8,
        "hunger_effect": 40,
        "mood_effect": 30,
        "cleanliness_effect": -3,
        "health_effect": 3,
        "category": "快餐"
    },
    {
        "name": "双层猪柳蛋堡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥓 早餐汉堡，双层猪柳配煎蛋和芝士",
        "sell_price": 35,
        "buy_price": 42,
        "affection_value": 0.9,
        "hunger_effect": 48,
        "mood_effect": 35,
        "cleanliness_effect": -6,
        "health_effect": -4,
        "category": "快餐"
    },
    {
        "name": "蜜汁手扒鸡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 特色炸鸡，蜜汁腌制的香甜手撕鸡肉",
        "sell_price": 28,
        "buy_price": 34,
        "affection_value": 0.7,
        "hunger_effect": 38,
        "mood_effect": 28,
        "cleanliness_effect": -5,
        "health_effect": -2,
        "category": "快餐"
    },
    {
        "name": "vivo50餐",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍗 疯狂疯狂星期四~疯狂疯狂v50~",
        "sell_price": 30,
        "buy_price": 50,
        "affection_value": 1.8,
        "hunger_effect": 60,
        "mood_effect": 22,
        "cleanliness_effect": -15,
        "health_effect": -15,
        "category": "滑稽"
    },
    # ===== 苍蝇馆子地方菜 =====
    {
        "name": "正宗兰州拉面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 地道兰州牛肉拉面，清香的汤头配上劲道的面条",
        "sell_price": 120,
        "buy_price": 320,
        "affection_value": 1.5,
        "hunger_effect": 60,
        "mood_effect": 45,
        "cleanliness_effect": -8,
        "health_effect": 10,
        "category": "地方菜"
    },
    {
        "name": "重庆小面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌶️ 重庆麻辣小面，香辣过瘾的经典川渝美味",
        "sell_price": 110,
        "buy_price": 300,
        "affection_value": 1.4,
        "hunger_effect": 55,
        "mood_effect": 50,
        "cleanliness_effect": -5,
        "health_effect": 5,
        "category": "地方菜"
    },
    {
        "name": "广式肠粉",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥢 广东茶楼经典肠粉，嫩滑米皮包裹鲜美馅料",
        "sell_price": 100,
        "buy_price": 280,
        "affection_value": 1.2,
        "hunger_effect": 50,
        "mood_effect": 40,
        "cleanliness_effect": 0,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "上海生煎包",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥟 上海老字号生煎包，外焦内嫩汁水丰富",
        "sell_price": 130,
        "buy_price": 350,
        "affection_value": 1.6,
        "hunger_effect": 65,
        "mood_effect": 48,
        "cleanliness_effect": -6,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "北京炸酱面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍝 老北京炸酱面，浓郁酱香配上爽口菜码",
        "sell_price": 115,
        "buy_price": 310,
        "affection_value": 1.3,
        "hunger_effect": 58,
        "mood_effect": 42,
        "cleanliness_effect": -7,
        "health_effect": 6,
        "category": "地方菜"
    },
    {
        "name": "西安肉夹馍",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥙 陕西特色肉夹馍，酥脆白吉馍夹香烂腊汁肉",
        "sell_price": 125,
        "buy_price": 330,
        "affection_value": 1.5,
        "hunger_effect": 62,
        "mood_effect": 46,
        "cleanliness_effect": -10,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "东北锅包肉",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 东北经典锅包肉，外酥内嫩酸甜可口",
        "sell_price": 140,
        "buy_price": 380,
        "affection_value": 1.7,
        "hunger_effect": 70,
        "mood_effect": 55,
        "cleanliness_effect": -12,
        "health_effect": 5,
        "category": "地方菜"
    },
    {
        "name": "湖南臭豆腐",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🧄 湖南长沙臭豆腐，闻着臭吃着香的独特美味",
        "sell_price": 90,
        "buy_price": 260,
        "affection_value": 1.1,
        "hunger_effect": 45,
        "mood_effect": 38,
        "cleanliness_effect": -15,
        "health_effect": 0,
        "category": "地方菜"
    },
    {
        "name": "云南过桥米线",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍲 云南特色过桥米线，鲜美高汤涮煮各式配菜",
        "sell_price": 135,
        "buy_price": 360,
        "affection_value": 1.6,
        "hunger_effect": 68,
        "mood_effect": 52,
        "cleanliness_effect": -3,
        "health_effect": 15,
        "category": "地方菜"
    },
    {
        "name": "新疆大盘鸡",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐔 新疆大盘鸡，香辣鸡肉配土豆宽面条",
        "sell_price": 150,
        "buy_price": 400,
        "affection_value": 1.8,
        "hunger_effect": 75,
        "mood_effect": 58,
        "cleanliness_effect": -10,
        "health_effect": 10,
        "category": "地方菜"
    },
    {
        "name": "四川麻婆豆腐",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌶️ 四川经典麻婆豆腐，麻辣鲜香下饭神器",
        "sell_price": 105,
        "buy_price": 290,
        "affection_value": 1.3,
        "hunger_effect": 52,
        "mood_effect": 44,
        "cleanliness_effect": -8,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "山东煎饼果子",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥞 天津山东煎饼果子，薄脆配鸡蛋的街头经典",
        "sell_price": 95,
        "buy_price": 270,
        "affection_value": 1.2,
        "hunger_effect": 48,
        "mood_effect": 40,
        "cleanliness_effect": -5,
        "health_effect": 6,
        "category": "地方菜"
    },
    {
        "name": "福建沙茶面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦐 福建沙茶面，独特沙茶酱调制的鲜香面条",
        "sell_price": 120,
        "buy_price": 320,
        "affection_value": 1.4,
        "hunger_effect": 58,
        "mood_effect": 46,
        "cleanliness_effect": -6,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "河南胡辣汤",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍯 河南胡辣汤，香辣浓稠的经典早餐汤品",
        "sell_price": 85,
        "buy_price": 250,
        "affection_value": 1.0,
        "hunger_effect": 42,
        "mood_effect": 35,
        "cleanliness_effect": -4,
        "health_effect": 5,
        "category": "地方菜"
    },
    {
        "name": "贵州酸汤鱼",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐟 贵州特色酸汤鱼，酸辣开胃的苗家风味",
        "sell_price": 160,
        "buy_price": 420,
        "affection_value": 1.9,
        "hunger_effect": 78,
        "mood_effect": 60,
        "cleanliness_effect": -8,
        "health_effect": 18,
        "category": "地方菜"
    },
    # ===== 超市新增商品 =====
    {
        "name": "关东煮",
        "weight": 8,
        "min_count": 1,
        "max_count": 2,
        "description": "🍢 日式关东煮，温热的汤汁配各种食材",
        "sell_price": 18,
        "buy_price": 35,
        "affection_value": 0.4,
        "hunger_effect": 25,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 5,
        "category": "日式料理"
    },
    {
        "name": "炒面面包",
        "weight": 6,
        "min_count": 1,
        "max_count": 1,
        "description": "🍞 日式炒面面包，面包里夹着香喷喷的炒面",
        "sell_price": 15,
        "buy_price": 28,
        "affection_value": 0.3,
        "hunger_effect": 30,
        "mood_effect": 15,
        "cleanliness_effect": -3,
        "health_effect": 0,
        "category": "日式料理"
    },
    {
        "name": "猪排饭团",
        "weight": 7,
        "min_count": 1,
        "max_count": 1,
        "description": "🍙 日式猪排饭团，香脆猪排配软糯米饭",
        "sell_price": 22,
        "buy_price": 42,
        "affection_value": 0.5,
        "hunger_effect": 35,
        "mood_effect": 25,
        "cleanliness_effect": -2,
        "health_effect": 8,
        "category": "日式料理"
    },
    {
        "name": "菠萝包",
        "weight": 8,
        "min_count": 1,
        "max_count": 2,
        "description": "🍍 港式菠萝包，酥脆表皮配松软内馅",
        "sell_price": 12,
        "buy_price": 25,
        "affection_value": 0.35,
        "hunger_effect": 22,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "港式茶餐厅"
    },
    {
        "name": "跳蛋",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥚 神秘的小玩具，据说能带来不一样的体验",
        "sell_price": 88,
        "buy_price": 199,
        "affection_value": 1.2,
        "hunger_effect": 0,
        "mood_effect": 233,
        "cleanliness_effect": -15,
        "health_effect": 233,
        "category": "成人用品"
    },
    {
        "name": "避孕套",
        "weight": 5,
        "min_count": 1,
        "max_count": 3,
        "description": "💊 安全防护用品，负责任的表现",
        "sell_price": 8,
        "buy_price": 15,
        "affection_value": 0.2,
        "hunger_effect": 0,
        "mood_effect": 88,
        "cleanliness_effect": -20,
        "health_effect": 88,
        "category": "成人用品"
    },
    # ===== 新增苍蝇馆子地方菜 =====
    {
        "name": "隆江猪脚饭",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 潮汕特色隆江猪脚饭，卤制猪脚香糯软烂",
        "sell_price": 145,
        "buy_price": 390,
        "affection_value": 1.7,
        "hunger_effect": 72,
        "mood_effect": 55,
        "cleanliness_effect": -10,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "柳州螺蛳粉",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐌 广西柳州螺蛳粉，酸辣鲜美的重口味米粉",
        "sell_price": 125,
        "buy_price": 340,
        "affection_value": 1.5,
        "hunger_effect": 60,
        "mood_effect": 48,
        "cleanliness_effect": -12,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "广式烧鹅",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦆 广东传统烧鹅，皮脆肉嫩油而不腻",
        "sell_price": 180,
        "buy_price": 480,
        "affection_value": 2.0,
        "hunger_effect": 85,
        "mood_effect": 68,
        "cleanliness_effect": -15,
        "health_effect": 15,
        "category": "地方菜"
    },
    {
        "name": "杭州西湖醋鱼",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐟 杭州名菜西湖醋鱼，酸甜清香的江南美味",
        "sell_price": 165,
        "buy_price": 440,
        "affection_value": 1.8,
        "hunger_effect": 75,
        "mood_effect": 62,
        "cleanliness_effect": -5,
        "health_effect": 20,
        "category": "地方菜"
    },
    {
        "name": "天津狗不理包子",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥟 天津老字号狗不理包子，皮薄馅大汁多",
        "sell_price": 155,
        "buy_price": 420,
        "affection_value": 1.8,
        "hunger_effect": 70,
        "mood_effect": 58,
        "cleanliness_effect": -8,
        "health_effect": 14,
        "category": "地方菜"
    },
    {
        "name": "苏州阳春面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 苏州传统阳春面，清汤细面简单而不简约",
        "sell_price": 118,
        "buy_price": 315,
        "affection_value": 1.4,
        "hunger_effect": 55,
        "mood_effect": 45,
        "cleanliness_effect": -3,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "成都夫妻肺片",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌶️ 成都经典夫妻肺片，麻辣鲜香的凉菜代表",
        "sell_price": 138,
        "buy_price": 370,
        "affection_value": 1.6,
        "hunger_effect": 65,
        "mood_effect": 52,
        "cleanliness_effect": -8,
        "health_effect": 10,
        "category": "地方菜"
    },
    {
        "name": "武汉热干面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 武汉特色热干面，浓郁芝麻酱拌制的干面",
        "sell_price": 112,
        "buy_price": 300,
        "affection_value": 1.3,
        "hunger_effect": 58,
        "mood_effect": 42,
        "cleanliness_effect": -6,
        "health_effect": 8,
        "category": "地方菜"
    },
    {
        "name": "长沙口味虾",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦐 长沙夜宵经典口味虾，麻辣鲜香的小龙虾",
        "sell_price": 170,
        "buy_price": 450,
        "affection_value": 1.9,
        "hunger_effect": 78,
        "mood_effect": 65,
        "cleanliness_effect": -18,
        "health_effect": 12,
        "category": "地方菜"
    },
    {
        "name": "东坡肘子",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 四川名菜东坡肘子，软糯香甜的传统川菜",
        "sell_price": 185,
        "buy_price": 490,
        "affection_value": 2.1,
        "hunger_effect": 88,
        "mood_effect": 70,
        "cleanliness_effect": -12,
        "health_effect": 18,
        "category": "地方菜"
    },
    {
        "name": "南京盐水鸭",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦆 南京特产盐水鸭，皮白肉嫩鲜美清淡",
        "sell_price": 158,
        "buy_price": 425,
        "affection_value": 1.8,
        "hunger_effect": 73,
        "mood_effect": 60,
        "cleanliness_effect": -6,
        "health_effect": 16,
        "category": "地方菜"
    },
    {
        "name": "沈阳白肉血肠",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 东北特色白肉血肠，浓郁的东北风味",
        "sell_price": 148,
        "buy_price": 395,
        "affection_value": 1.7,
        "hunger_effect": 70,
        "mood_effect": 55,
        "cleanliness_effect": -8,
        "health_effect": 14,
        "category": "地方菜"
    },
    {
        "name": "太原刀削面",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 山西特色刀削面，刀削出的独特面条形状",
        "sell_price": 115,
        "buy_price": 308,
        "affection_value": 1.3,
        "hunger_effect": 56,
        "mood_effect": 44,
        "cleanliness_effect": -5,
        "health_effect": 9,
        "category": "地方菜"
    },
    {
        "name": "宁夏手抓羊肉",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐑 宁夏传统手抓羊肉，鲜嫩无膻味的西北特色",
        "sell_price": 195,
        "buy_price": 520,
        "affection_value": 2.2,
        "hunger_effect": 92,
        "mood_effect": 75,
        "cleanliness_effect": -15,
        "health_effect": 22,
        "category": "地方菜"
    },
    {
        "name": "内蒙古烤羊腿",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍖 内蒙古烤羊腿，草原上的豪放美食",
        "sell_price": 220,
        "buy_price": 580,
        "affection_value": 2.5,
        "hunger_effect": 100,
        "mood_effect": 85,
        "cleanliness_effect": -20,
        "health_effect": 25,
        "category": "地方菜"
    },
    # ===== 超市新增商品 =====
    {
        "name": "泡泡球",
        "weight": 8,
        "min_count": 1,
        "max_count": 3,
        "description": "🔮 五彩斑斓的泡泡球，玩起来特别解压",
        "sell_price": 10,
        "buy_price": 25,
        "affection_value": 0.3,
        "hunger_effect": 0,
        "mood_effect": 22,
        "cleanliness_effect": -2,
        "health_effect": 0,
        "category": "玩具"
    },
    {
        "name": "老坛酸菜牛肉面",
        "weight": 7,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 经典方便面，酸爽可口的酸菜搭配鲜美牛肉",
        "sell_price": 5,
        "buy_price": 12,
        "affection_value": 0.2,
        "hunger_effect": 35,
        "mood_effect": 10,
        "cleanliness_effect": -2,
        "health_effect": -2,
        "category": "食物"
    },
    {
        "name": "红烧牛肉面",
        "weight": 7,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 浓郁的红烧牛肉面，回味经典",
        "sell_price": 5,
        "buy_price": 12,
        "affection_value": 0.2,
        "hunger_effect": 35,
        "mood_effect": 10,
        "cleanliness_effect": -2,
        "health_effect": -2,
        "category": "食物"
    },
    {
        "name": "鲜虾鱼板面",
        "weight": 6,
        "min_count": 1,
        "max_count": 1,
        "description": "🦐 鲜虾和鱼板的美味搭配，海鲜风味十足",
        "sell_price": 6,
        "buy_price": 15,
        "affection_value": 0.25,
        "hunger_effect": 30,
        "mood_effect": 12,
        "cleanliness_effect": -2,
        "health_effect": -1,
        "category": "食物"
    },
    {
        "name": "纳豆",
        "weight": 4,
        "min_count": 1,
        "max_count": 1,
        "description": "🥢 日本传统发酵豆制品，黏糊糊的但营养丰富",
        "sell_price": 8,
        "buy_price": 20,
        "affection_value": 0.15,
        "hunger_effect": 25,
        "mood_effect": 5,
        "cleanliness_effect": -5,
        "health_effect": 10,
        "category": "食物"
    },
    {
        "name": "老干妈",
        "weight": 5,
        "min_count": 1,
        "max_count": 1,
        "description": "🌶️ 贵州特产辣椒酱，下饭神器",
        "sell_price": 10,
        "buy_price": 25,
        "affection_value": 0.3,
        "hunger_effect": 10,
        "mood_effect": 15,
        "cleanliness_effect": -8,
        "health_effect": 2,
        "category": "调味品"
    },
    {
        "name": "鲷鱼烧",
        "weight": 6,
        "min_count": 1,
        "max_count": 2,
        "description": "🐠 日式鱼形状甜点，内馅红豆沙香甜可口",
        "sell_price": 8,
        "buy_price": 20,
        "affection_value": 0.35,
        "hunger_effect": 25,
        "mood_effect": 18,
        "cleanliness_effect": -2,
        "health_effect": 2,
        "category": "食物"
    },
    {
        "name": "茶叶蛋",
        "weight": 10,
        "min_count": 1,
        "max_count": 3,
        "description": "🥚 茶香浓郁的卤蛋，方便又美味的小食",
        "sell_price": 3,
        "buy_price": 8,
        "affection_value": 0.15,
        "hunger_effect": 20,
        "mood_effect": 8,
        "cleanliness_effect": -1,
        "health_effect": 5,
        "category": "食物"
    },
    {
        "name": "旺旺碎冰冰",
        "weight": 8,
        "min_count": 1,
        "max_count": 2,
        "description": "🧊 童年回忆的碎冰饮料，各种水果味清凉解暑",
        "sell_price": 4,
        "buy_price": 10,
        "affection_value": 0.2,
        "hunger_effect": 5,
        "mood_effect": 20,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "饮料"
    },
    {
        "name": "伊利巧乐兹",
        "weight": 7,
        "min_count": 1,
        "max_count": 2,
        "description": "🍦 经典的巧克力雪糕，酥脆外层裹着细滑冰淇淋",
        "sell_price": 5,
        "buy_price": 12,
        "affection_value": 0.25,
        "hunger_effect": 15,
        "mood_effect": 22,
        "cleanliness_effect": 0,
        "health_effect": -2,
        "category": "冷饮"
    },
    {
        "name": "小布丁雪糕",
        "weight": 8,
        "min_count": 1,
        "max_count": 2,
        "description": "🍮 香甜的小布丁雪糕，入口即化",
        "sell_price": 3,
        "buy_price": 8,
        "affection_value": 0.2,
        "hunger_effect": 10,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": -1,
        "category": "冷饮"
    },
    {
        "name": "龟苓膏",
        "weight": 5,
        "min_count": 1,
        "max_count": 1,
        "description": "🥣 广东传统甜品，清凉解毒养生",
        "sell_price": 12,
        "buy_price": 30,
        "affection_value": 0.4,
        "hunger_effect": 12,
        "mood_effect": 15,
        "cleanliness_effect": 0,
        "health_effect": 18,
        "category": "甜品"
    },
    {
        "name": "芝麻糊",
        "weight": 6,
        "min_count": 1,
        "max_count": 1,
        "description": "🥣 浓郁的黑芝麻糊，香甜滋补",
        "sell_price": 10,
        "buy_price": 25,
        "affection_value": 0.35,
        "hunger_effect": 20,
        "mood_effect": 18,
        "cleanliness_effect": 0,
        "health_effect": 15,
        "category": "甜品"
    },
    {
        "name": "初音未来味汽水",
        "weight": 3,
        "min_count": 1,
        "max_count": 1,
        "description": "🥤 葱味汽水，喝了会让你忍不住唱《甩葱歌》",
        "sell_price": 20,
        "buy_price": 39,
        "affection_value": 0.5,
        "hunger_effect": 8,
        "mood_effect": 39,
        "cleanliness_effect": 0,
        "health_effect": -5,
        "category": "滑稽"
    },
    
    # ===== 新增工业化菜品 =====
    {
        "name": "预制菜",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥘 工厂流水线生产的预制菜，便宜大碗但对健康不太友好",
        "sell_price": 25,
        "buy_price": 50,
        "affection_value": 0.3,
        "hunger_effect": 110,
        "mood_effect": -8,
        "cleanliness_effect": -5,
        "health_effect": -35,
        "category": "工业化菜品"
    },
    {
        "name": "拼好饭",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍱 预先拼装好的盒饭，价格实惠分量足，但营养和卫生堪忧",
        "sell_price": 30,
        "buy_price": 65,
        "affection_value": 0.4,
        "hunger_effect": 125,
        "mood_effect": -10,
        "cleanliness_effect": -8,
        "health_effect": -40,
        "category": "工业化菜品"
    },

    # ===== 旅行纪念品 =====
    # 北京纪念品（不通过出门转转获得，仅在旅行中获得）
    {
        "name": "北京烤鸭真空装",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦆 正宗北京烤鸭，回味无穷",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 180,
        "mood_effect": 120,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "故宫文创胶带",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🏮 故宫联名文创，颜值超高",
        "sell_price": 50,
        "affection_value": 0.3,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "景泰蓝花瓶",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🏺 精美的景泰蓝工艺品，可大幅提升心情",
        "sell_price": 50,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 200,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "熊猫玩偶",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐼 可爱的熊猫公仔，心情大好",
        "sell_price": 50,
        "affection_value": 0.9,
        "hunger_effect": 0,
        "mood_effect": 220,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "中国结挂饰",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🪢 传统手工编织，寓意吉祥",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 120,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "麻将钥匙扣",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🀄 迷你麻将，手气加成",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 130,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "文房四宝套装",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "📜 笔墨纸砚，书香气质",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "藏式转经筒",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "📿 佛教法器，内心平静",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },

    # 杭州纪念品
    {
        "name": "龙井茶叶礼盒",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍵 正宗西湖龙井，有益身心健康",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 100,
        "category": "纪念品"
    },
    {
        "name": "西湖龙井护手霜",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌿 茶香护肤，温润如玉",
        "sell_price": 50,
        "affection_value": 0.3,
        "hunger_effect": 0,
        "mood_effect": 80,
        "cleanliness_effect": 30,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "杭州丝绸眼罩",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "😴 真丝眼罩，美容觉神器",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 80,
        "cleanliness_effect": 20,
        "health_effect": 50,
        "category": "纪念品"
    },
    {
        "name": "丝绸围巾",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🧣 柔滑的真丝围巾，增加魅力",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 150,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "青花瓷茶具",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🫖 典雅的青花瓷，提升气质",
        "sell_price": 50,
        "affection_value": 0.7,
        "hunger_effect": 0,
        "mood_effect": 180,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "古典扇子",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🪭 精致折扇，古典美人必备",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 80,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "苏州刺绣手帕",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🧵 精美刺绣，工艺精湛",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 70,
        "cleanliness_effect": 20,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "竹制茶杯",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🎋 竹香淡雅，禅意生活",
        "sell_price": 50,
        "affection_value": 0.3,
        "hunger_effect": 0,
        "mood_effect": 80,
        "cleanliness_effect": 0,
        "health_effect": 80,
        "category": "纪念品"
    },

    # 云南纪念品
    {
        "name": "云南鲜花饼",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌹 玫瑰花香，甜蜜浪漫",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 100,
        "mood_effect": 140,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "普洱茶饼",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍃 陈年普洱，越品越香",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 90,
        "cleanliness_effect": 0,
        "health_effect": 150,
        "category": "纪念品"
    },
    {
        "name": "岭南荔枝干",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍒 甜蜜荔枝，南国风情",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 90,
        "mood_effect": 120,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "民族风银饰",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "💍 云南银饰，民族风情",
        "sell_price": 50,
        "affection_value": 0.7,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "玉龙雪山水晶",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "💎 雪山水晶，纯净透明",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 20,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "大理扎染围巾",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🎨 传统扎染，艺术气息",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 90,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "丽江古城木雕",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🪵 纳西木雕，古城记忆",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "云南过桥米线调料",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 正宗调料，家的味道",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 160,
        "mood_effect": 80,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },

    # 西安纪念品
    {
        "name": "兵马俑巧克力",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🗿 创意巧克力，萌翻了",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 120,
        "mood_effect": 150,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "陕西肉夹馍调料包",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥙 正宗调料，家乡味道",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 160,
        "mood_effect": 110,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "唐装旗袍",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "👘 传统服饰，优雅迷人",
        "sell_price": 50,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 80,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "大雁塔香囊",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "📿 佛塔香囊，宁神静气",
        "sell_price": 50,
        "affection_value": 0.7,
        "hunger_effect": 0,
        "mood_effect": 140,
        "cleanliness_effect": 0,
        "health_effect": 100,
        "category": "纪念品"
    },
    {
        "name": "西安城墙砖茶",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🧱 古城茶砖，厚重历史",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 90,
        "cleanliness_effect": 0,
        "health_effect": 120,
        "category": "纪念品"
    },
    {
        "name": "大雁塔模型",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🗼 古塔模型，智慧之光",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 180,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "陕西剪纸艺术",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "✂️ 民间剪纸，传统技艺",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 120,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "凉皮调料包",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍝 西安凉皮，清爽解腻",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 140,
        "mood_effect": 90,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },

    # 大阪纪念品
    {
        "name": "章鱼小丸子模型",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐙 大阪特色，超萌章鱼烧",
        "sell_price": 50,
        "affection_value": 0.7,
        "hunger_effect": 0,
        "mood_effect": 180,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "大阪烧调料包",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍳 正宗大阪烧，家庭制作",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 160,
        "mood_effect": 120,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "心斋桥购物袋",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🛍️ 时尚购物袋，潮流标志",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "道顿堀霓虹灯模型",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌃 繁华夜景，霓虹闪烁",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 110,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "大阪城钥匙扣",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🏰 古城记忆，历史传承",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 90,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "和牛肉干",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥩 顶级和牛，入口即化",
        "sell_price": 50,
        "affection_value": 0.8,
        "hunger_effect": 150,
        "mood_effect": 120,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "关西腔学习手册",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "📚 关西方言，幽默风趣",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "大阪环球影城纪念品",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🎢 影城特色，刺激回忆",
        "sell_price": 50,
        "affection_value": 0.9,
        "hunger_effect": 0,
        "mood_effect": 150,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },

    # 东京纪念品
    {
        "name": "哆啦A梦手办",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🤖 蓝胖子手办，童心满满",
        "sell_price": 50,
        "affection_value": 0.9,
        "hunger_effect": 0,
        "mood_effect": 220,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "浅草寺御守",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🧿 祈福御守，神明庇佑",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "秋叶原扭蛋",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥚 限定扭蛋，开盲盒的快乐",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 160,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "东京香蕉糕点",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍌 东京特产，香甜可口",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 110,
        "mood_effect": 130,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "高达模型",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🤖 机甲模型，男人的浪漫",
        "sell_price": 50,
        "affection_value": 0.7,
        "hunger_effect": 0,
        "mood_effect": 180,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "柴犬玩偶",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐕 柴犬玩偶，忠诚可爱",
        "sell_price": 50,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 200,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "动漫周边徽章",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🏷️ 动漫徽章，二次元之魂",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 120,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "涩谷十字路口模型",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🚦 繁忙十字路口，都市印象",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 110,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },

    # 仰光纪念品
    {
        "name": "翡翠手镯",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "💚 缅甸翡翠，温润如玉",
        "sell_price": 50,
        "affection_value": 1.0,
        "hunger_effect": 0,
        "mood_effect": 150,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "瑞光大金塔纪念品",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🏛️ 圣地纪念品，灵性满满",
        "sell_price": 50,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 120,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "缅甸红宝石",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "💎 珍贵红宝石，价值连城",
        "sell_price": 50,
        "affection_value": 1.2,
        "hunger_effect": 0,
        "mood_effect": 200,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "佛像挂件",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🧿 佛教护身符，内心安宁",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 120,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "茵雅湖珍珠",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🤍 淡水珍珠，温润光泽",
        "sell_price": 50,
        "affection_value": 0.7,
        "hunger_effect": 0,
        "mood_effect": 140,
        "cleanliness_effect": 30,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "缅甸特色面条",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🍜 椰奶面条，异国美味",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 160,
        "mood_effect": 80,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "传统龙基服饰",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "👗 缅甸传统服装，异域风情",
        "sell_price": 50,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 90,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "仰光街头小食",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🥘 街头美食，冒险味蕾",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 140,
        "mood_effect": 80,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },

    # 开罗纪念品
    {
        "name": "法老黄金项链",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "👑 古埃及风格，尊贵典雅",
        "sell_price": 50,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 180,
        "cleanliness_effect": 50,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "金字塔水晶球",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🔮 神秘水晶，蕴含古老智慧",
        "sell_price": 50,
        "affection_value": 0.7,
        "hunger_effect": 0,
        "mood_effect": 160,
        "cleanliness_effect": 0,
        "health_effect": 80,
        "category": "纪念品"
    },
    {
        "name": "尼罗河莎草纸画",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "📜 手工绘制，记录古代传说",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 140,
        "cleanliness_effect": 0,
        "health_effect": 60,
        "category": "纪念品"
    },
    {
        "name": "埃及艳后化妆盒",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "💄 精美化妆盒，重现古典美丽",
        "sell_price": 50,
        "affection_value": 0.9,
        "hunger_effect": 0,
        "mood_effect": 120,
        "cleanliness_effect": 150,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "圣甲虫护身符",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🪲 古埃及护符，带来好运",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 90,
        "cleanliness_effect": 0,
        "health_effect": 100,
        "category": "纪念品"
    },
    {
        "name": "法老面具复制品",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "👤 图坦卡蒙面具，威严神圣",
        "sell_price": 50,
        "affection_value": 1.0,
        "hunger_effect": 0,
        "mood_effect": 200,
        "cleanliness_effect": 40,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "阿拉伯香料盒",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌿 传统香料，异域芬芳",
        "sell_price": 50,
        "affection_value": 0.4,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 120,
        "category": "纪念品"
    },
    {
        "name": "沙漠玫瑰水",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌹 沙漠之花，清香怡人",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 0,
        "mood_effect": 110,
        "cleanliness_effect": 120,
        "health_effect": 0,
        "category": "纪念品"
    },

    # 迪拜纪念品
    {
        "name": "黄金手镯",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "💛 纯金制品，奢华尊贵",
        "sell_price": 50,
        "affection_value": 1.2,
        "hunger_effect": 0,
        "mood_effect": 220,
        "cleanliness_effect": 60,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "哈利法塔模型",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🏗️ 世界最高塔，摩天奇迹",
        "sell_price": 50,
        "affection_value": 0.8,
        "hunger_effect": 0,
        "mood_effect": 180,
        "cleanliness_effect": 0,
        "health_effect": 80,
        "category": "纪念品"
    },
    {
        "name": "阿拉伯香水",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "💐 中东香氛，神秘诱人",
        "sell_price": 50,
        "affection_value": 1.0,
        "hunger_effect": 0,
        "mood_effect": 140,
        "cleanliness_effect": 180,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "骆驼毛围巾",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🐫 沙漠之舟，温暖柔软",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 120,
        "cleanliness_effect": 100,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "波斯地毯",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🪴 手工编织，艺术珍品",
        "sell_price": 50,
        "affection_value": 1.1,
        "hunger_effect": 0,
        "mood_effect": 200,
        "cleanliness_effect": 0,
        "health_effect": 100,
        "category": "纪念品"
    },
    {
        "name": "椰枣礼盒",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌴 沙漠甘露，营养丰富",
        "sell_price": 50,
        "affection_value": 0.5,
        "hunger_effect": 150,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "帆船酒店纪念品",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🏨 七星奢华，传奇酒店",
        "sell_price": 50,
        "affection_value": 1.0,
        "hunger_effect": 0,
        "mood_effect": 190,
        "cleanliness_effect": 0,
        "health_effect": 90,
        "category": "纪念品"
    },
    {
        "name": "沙画瓶",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🏺 彩色沙画，沙漠艺术",
        "sell_price": 50,
        "affection_value": 0.6,
        "hunger_effect": 0,
        "mood_effect": 130,
        "cleanliness_effect": 80,
        "health_effect": 0,
        "category": "纪念品"
    },

    # 亚特兰蒂斯纪念品
    {
        "name": "水晶项链",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "💎 深海水晶制成，散发神秘蓝光",
        "sell_price": 200,
        "affection_value": 2.0,
        "hunger_effect": 0,
        "mood_effect": 300,
        "cleanliness_effect": 150,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "海神护身符",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🔱 海神波塞冬的祝福，庇护航海平安",
        "sell_price": 200,
        "affection_value": 1.8,
        "hunger_effect": 0,
        "mood_effect": 180,
        "cleanliness_effect": 0,
        "health_effect": 200,
        "category": "纪念品"
    },
    {
        "name": "深海珍珠",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🦪 万年深海孕育，价值连城",
        "sell_price": 200,
        "affection_value": 1.5,
        "hunger_effect": 0,
        "mood_effect": 150,
        "cleanliness_effect": 200,
        "health_effect": 0,
        "category": "纪念品"
    },
    {
        "name": "亚特兰蒂斯音乐盒",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🎵 播放远古海族乐曲，令人心旷神怡",
        "sell_price": 200,
        "affection_value": 2.2,
        "hunger_effect": 0,
        "mood_effect": 250,
        "cleanliness_effect": 0,
        "health_effect": 120,
        "category": "纪念品"
    },
    {
        "name": "智慧之书",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "📖 记录失落文明的智慧，开启心灵",
        "sell_price": 200,
        "affection_value": 1.7,
        "hunger_effect": 0,
        "mood_effect": 200,
        "cleanliness_effect": 0,
        "health_effect": 180,
        "category": "纪念品"
    },
    {
        "name": "能量水晶",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "⚡ 蕴含古老能量，滋养身心",
        "sell_price": 200,
        "affection_value": 1.9,
        "hunger_effect": 0,
        "mood_effect": 100,
        "cleanliness_effect": 0,
        "health_effect": 250,
        "category": "纪念品"
    },
    {
        "name": "海洋精华",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🌊 纯净的海洋精华，美容养颜",
        "sell_price": 200,
        "affection_value": 1.6,
        "hunger_effect": 0,
        "mood_effect": 0,
        "cleanliness_effect": 180,
        "health_effect": 150,
        "category": "纪念品"
    },
    {
        "name": "神话雕像",
        "weight": 0,
        "min_count": 1,
        "max_count": 1,
        "description": "🗿 海神与美人鱼的传说雕像",
        "sell_price": 200,
        "affection_value": 2.1,
        "hunger_effect": 0,
        "mood_effect": 280,
        "cleanliness_effect": 0,
        "health_effect": 100,
        "category": "纪念品"
    }
]
