"""工作配置文件 - 所有可用工作的定义"""

# 工作列表配置
WORK_LIST = [
    {
        "id": 1,
        "name": "捡废品",
        "pay": 200,
        "duration": 2,
        "description": "在街道上寻找可回收的废品，虽然脏累但是入门工作",
        "hunger_cost": 15,
        "cleanliness_cost": 25,
        "mood_cost": 10,
        "health_cost": 5,
        "growth_reward": 8,
        "level_required": 1,
        "education_required": 0
    },
    {
        "id": 2,
        "name": "群里搬屎",
        "pay": 100,
        "duration": 1,
        "description": "在各种群里搬运表情包和沙雕内容，虽然轻松但略显无聊",
        "hunger_cost": 5,
        "cleanliness_cost": 5,
        "mood_cost": 15,
        "health_cost": 0,
        "growth_reward": 5,
        "level_required": 1,
        "education_required": 0
    },
    {
        "id": 3,
        "name": "发传单",
        "pay": 500,
        "duration": 3,
        "description": "在商业街发放广告传单，需要一定的沟通能力",
        "hunger_cost": 20,
        "cleanliness_cost": 15,
        "mood_cost": 5,
        "health_cost": 8,
        "growth_reward": 12,
        "level_required": 2,
        "education_required": 1
    },
    {
        "id": 4,
        "name": "便利店营业员",
        "pay": 1200,
        "duration": 8,
        "description": "在便利店做收银和理货工作，需要基本算数能力",
        "hunger_cost": 25,
        "cleanliness_cost": 10,
        "mood_cost": 8,
        "health_cost": 10,
        "growth_reward": 15,
        "level_required": 2,
        "education_required": 1
    },
    {
        "id": 5,
        "name": "群里当男娘",
        "pay": 3200,
        "duration": 8,
        "description": "在群里扮演可爱男娘角色，需要一定的表演天赋和脸皮厚度",
        "hunger_cost": 10,
        "cleanliness_cost": 5,
        "mood_cost": 5,
        "health_cost": 0,
        "growth_reward": 20,
        "level_required": 3,
        "education_required": 1
    },
    {
        "id": 6,
        "name": "餐厅服务员",
        "pay": 4000,
        "duration": 8,
        "description": "在餐厅为客人点餐和送餐，需要良好的服务意识",
        "hunger_cost": 30,
        "cleanliness_cost": 20,
        "mood_cost": 12,
        "health_cost": 15,
        "growth_reward": 18,
        "level_required": 3,
        "education_required": 2
    },
    {
        "id": 7,
        "name": "快递配送员",
        "pay": 4500,
        "duration": 8,
        "description": "骑车或步行配送快递包裹，需要体力和路线规划能力",
        "hunger_cost": 40,
        "cleanliness_cost": 25,
        "mood_cost": 10,
        "health_cost": 20,
        "growth_reward": 20,
        "level_required": 4,
        "education_required": 2
    },
    {
        "id": 8,
        "name": "宠物店助理",
        "pay": 5000,
        "duration": 8,
        "description": "帮助照顾宠物店的小动物，需要爱心和耐心",
        "hunger_cost": 20,
        "cleanliness_cost": 20,
        "mood_cost": -5,
        "health_cost": 8,
        "growth_reward": 15,
        "level_required": 5,
        "education_required": 2
    },
    {
        "id": 9,
        "name": "图书馆管理员",
        "pay": 5500,
        "duration": 8,
        "description": "在图书馆整理图书和协助读者，需要一定的文化基础",
        "hunger_cost": 20,
        "cleanliness_cost": 5,
        "mood_cost": -8,
        "health_cost": 5,
        "growth_reward": 20,
        "level_required": 5,
        "education_required": 3
    },
    {
        "id": 10,
        "name": "女仆咖啡厅服务员",
        "pay": 8888,
        "duration": 8,
        "description": "在女仆咖啡厅为客人服务，需要较高的颜值和服务技巧",
        "hunger_cost": 25,
        "cleanliness_cost": 15,
        "mood_cost": 5,
        "health_cost": 10,
        "growth_reward": 35,
        "level_required": 6,
        "education_required": 3
    },
    {
        "id": 11,
        "name": "家教老师",
        "pay": 9000,
        "duration": 8,
        "description": "为学生提供课外辅导，需要扎实的学科基础",
        "hunger_cost": 15,
        "cleanliness_cost": 5,
        "mood_cost": -12,
        "health_cost": 5,
        "growth_reward": 25,
        "level_required": 7,
        "education_required": 4
    },
    {
        "id": 12,
        "name": "翻译助理",
        "pay": 12000,
        "duration": 8,
        "description": "协助处理文件翻译工作，需要较高的语言能力",
        "hunger_cost": 20,
        "cleanliness_cost": 5,
        "mood_cost": -8,
        "health_cost": 8,
        "growth_reward": 28,
        "level_required": 8,
        "education_required": 5
    },
    {
        "id": 13,
        "name": "活动策划助手",
        "pay": 12500,
        "duration": 8,
        "description": "协助策划和执行各种活动，需要创意和组织能力",
        "hunger_cost": 30,
        "cleanliness_cost": 12,
        "mood_cost": -3,
        "health_cost": 15,
        "growth_reward": 30,
        "level_required": 10,
        "education_required": 5
    },
    {
        "id": 14,
        "name": "私人助理",
        "pay": 13000,
        "duration": 8,
        "description": "为企业高管提供日常助理服务，需要高度的专业素养",
        "hunger_cost": 20,
        "cleanliness_cost": 8,
        "mood_cost": 5,
        "health_cost": 10,
        "growth_reward": 35,
        "level_required": 15,
        "education_required": 6
    },
    {
        "id": 15,
        "name": "科研助理",
        "pay": 20000,
        "duration": 12,
        "description": "协助进行学术研究工作，需要极高的学术水平",
        "hunger_cost": 25,
        "cleanliness_cost": 5,
        "mood_cost": -10,
        "health_cost": 15,
        "growth_reward": 40,
        "level_required": 20,
        "education_required": 7
    }
]
